import { startAuthentication } from '@simplewebauthn/browser'

const object=v=>!!v&&typeof v==='object'&&!Array.isArray(v)
const id=v=>typeof v==='string'&&/^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$/.test(v)
const uuid=v=>typeof v==='string'&&/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(v)
const positive=v=>Number.isSafeInteger(v)&&v>0
const count=v=>Number.isSafeInteger(v)&&v>=0
const digest=v=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v)
const text=(v,max=4000)=>typeof v==='string'&&v.length>0&&v.length<=max&&!/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(v)
const iso=v=>typeof v==='string'&&/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString()===v
const purpose=v=>v==='work'||v==='entry'
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const clone=v=>JSON.parse(JSON.stringify(v))
const HOLDS={unconfigured:'The property’s review process is not configured.',not_required:'This permission is not required for this plan.',missing_plan:'A current work plan is needed.',spending_not_authorized:'The property spending decision is not ready.',emergency:'This request needs the property emergency process.',context_changed:'The apartment or resident context needs review.',policy_changed:'The property rules changed.',roster_changed:'The required decision-makers need review.',authority_changed:'Decision authority needs review.',binding_changed:'Resident account access needs review.',account_changed:'Account security changed.',factor_revoked:'The signing passkey is no longer active.',terms_changed:'The work terms changed.',request_withdrawn:'The property withdrew this review.',response_expired:'The response deadline passed.',consent_expired:'The permission period ended.',entry_expired:'The proposed entry window ended.',missing_entry_window:'The property must propose an entry window.',missing_required_recipient:'A required decision-maker is missing.',awaiting_decisions:'Required decisions are still pending.',declined:'A required decision is declined.',revoked:'Permission has been revoked.',job_already_committed:'This job already has a recorded external commitment; contact the property team.'}
const ERRORS={mfa_required:'Verify your resident sign-in with your own passkey, then return to this review.',consent_unauthenticated:'Your resident sign-in ended.',consent_forbidden:'Your current account cannot access this review.',account_changed:'The signed-in account changed.',invalid_consent_form:'This review form is no longer current.',consent_changed:'The review or authority changed. Refresh before making a new decision.',consent_held:'This decision is held by the current terms or authority.',consent_not_found:'This review is not available to your account.',consent_passkey_required:'Use an active resident passkey for this exact decision.',consent_ceremony_used:'That verification cannot be reused. Check the saved decision.',consent_rate_limited:'Too many attempts. Wait before trying again.'}
class Unconfirmed extends Error {}
class Rejected extends Error {constructor(code,status){super(ERRORS[code]||'The result could not be confirmed.');this.code=code;this.status=status}}
const fail=()=>{throw new Unconfirmed()}
function readHelp(v){if(v===null)return null;if(!object(v)||!text(v.label,120)||!text(v.phone,32)||!/^\+?[0-9 ()-]{6,32}$/.test(v.phone)||!text(v.emergencyInstructions,4000)||!(v.url===null||text(v.url,2048)))return fail();if(v.url!==null){let u;try{u=new URL(v.url)}catch{return fail()}if(u.protocol!=='https:'||u.username||u.password)return fail()}return{label:v.label,phone:v.phone,url:v.url,emergencyInstructions:v.emergencyInstructions}}
function readTerms(v){
  if(!object(v)||v.schemaVersion!==1||!purpose(v.purpose)||!text(v.propertyName,200)||!id(v.unitId)||!text(v.publicSummary,4000)||!text(v.scopeOfWork,8000)||!object(v.party)||!['vendor','internal'].includes(v.party.kind)||!text(v.party.name,200)||v.party.kind==='vendor'&&(!uuid(v.party.id)||!positive(v.party.version))||v.funding!=='property_no_resident_charge'||v.currency!=='USD'||!count(v.propertyMaximumCents)||v.propertyMaximumCents>1e9||v.residentChargeCents!==0||!text(v.noChargeStatement,4000)||!['no_unit_entry','unit_entry'].includes(v.accessRequirement)||typeof v.conditions!=='string'||v.conditions.length>4000)return fail()
  const w=v.entryWindow
  if(w!==null){if(!object(w)||!iso(w.startsAt)||!iso(w.endsAt)||Date.parse(w.endsAt)<=Date.parse(w.startsAt)||!text(w.timeZone,100)||![w.startsLocal,w.endsLocal].every(s=>typeof s==='string'&&/^\d{4}-\d\d-\d\dT\d\d:\d\d(?::\d\d(?:\.\d{3})?)?[+-]\d\d:\d\d$/.test(s))||Date.parse(w.startsLocal)!==Date.parse(w.startsAt)||Date.parse(w.endsLocal)!==Date.parse(w.endsAt))return fail();try{for(const [utc,local] of [[w.startsAt,w.startsLocal],[w.endsAt,w.endsLocal]]){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:w.timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(utc)).map(x=>[x.type,x.value]));if(`${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}:${p.second}`!==local.slice(0,19))return fail()}}catch{return fail()}}
  if(v.purpose==='work'&&w!==null||v.accessRequirement==='no_unit_entry'&&w!==null)return fail()
  return clone(v)
}
function readEffect(v){if(!object(v)||typeof v.required!=='boolean'||typeof v.effective!=='boolean'||!Array.isArray(v.holds)||v.holds.some(h=>!Object.hasOwn(HOLDS,h))||!iso(v.evaluatedAt)||!(v.refreshAt===null||iso(v.refreshAt))||v.dispatchStatus!=='not_dispatched'||v.notificationStatus!=='not_sent')return fail();return clone(v)}
function readDecision(v,b,request){if(v===null)return null;if(!object(v)||!uuid(v.id)||v.requestId!==request.requestId||!positive(v.requestVersion)||v.purpose!==request.purpose||!positive(v.version)||v.actorUserId!==b.userId||!['grant','decline','revoke'].includes(v.decision)||!(v.grantId===null||uuid(v.grantId))||!digest(v.termsDigest)||!iso(v.decidedAt))return fail();return clone(v)}
function readDetail(v,b,requestId){
  if(!object(v)||v.requestId!==requestId||!positive(v.requestVersion)||!purpose(v.purpose)||!digest(v.termsDigest)||!digest(v.materialDigest)||!iso(v.responseDeadline)||!iso(v.consentValidUntil)||!iso(v.publishedAt)||!(v.withdrawnAt===null||iso(v.withdrawnAt))||!count(v.ownDecisionVersion)||['canGrant','canDecline','canRevoke','requiresPasskey','currentTerms'].some(k=>typeof v[k]!=='boolean'))return fail()
  const terms=readTerms(v.terms),effectiveness=readEffect(v.effectiveness),ownDecision=readDecision(v.ownDecision,b,v),help=readHelp(v.help)
  if(terms.purpose!==v.purpose||ownDecision&&ownDecision.version!==v.ownDecisionVersion||!ownDecision&&v.ownDecisionVersion!==0||v.canRevoke&&ownDecision?.decision!=='grant'||v.canGrant&&(!v.currentTerms||!effectiveness.required||v.purpose==='entry'&&!terms.entryWindow))return fail()
  return {...clone(v),terms,effectiveness,ownDecision,help}
}
function readCursor(v){if(v===null)return null;if(!object(v)||!iso(v.createdAt)||!uuid(v.id))return fail();return{createdAt:v.createdAt,id:v.id}}
function readPage(v){if(!object(v)||!Array.isArray(v.items)||v.items.length>50||!iso(v.evaluatedAt)||!(v.refreshAt===null||iso(v.refreshAt)))return fail();const items=v.items.map(r=>{if(!object(r)||!uuid(r.requestId)||!positive(r.requestVersion)||!purpose(r.purpose)||!text(r.propertyName,200)||!id(r.unitId)||!text(r.publicSummary,4000)||!iso(r.responseDeadline)||!iso(r.consentValidUntil)||!iso(r.publishedAt)||![null,'grant','decline','revoke'].includes(r.ownDecision)||typeof r.effective!=='boolean'||typeof r.currentTerms!=='boolean'||!Array.isArray(r.holds)||r.holds.some(h=>!Object.hasOwn(HOLDS,h)))return fail();return clone(r)});if(new Set(items.map(r=>r.requestId)).size!==items.length)return fail();return{items,nextCursor:readCursor(v.nextCursor),evaluatedAt:v.evaluatedAt,refreshAt:v.refreshAt}}
function readReceipt(v,b,marker){if(v===null)return null;if(!object(v)||v.commandId!==marker.commandId||v.actorUserId!==b.userId||v.resource!=='decision'||!uuid(v.id)||!positive(v.version)||v.requestId!==marker.requestId||v.purpose!==marker.purpose||!positive(v.requestVersion)||!['grant','decline','revoke'].includes(v.action)||marker.action&&v.action!==marker.action||marker.expectedDecisionVersion!==undefined&&v.version!==marker.expectedDecisionVersion+1||marker.requestVersion!==undefined&&v.requestVersion!==marker.requestVersion||!iso(v.committedAt)||typeof v.replayed!=='boolean'||v.outcome!=='saved')return fail();return clone(v)}
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v/100)
const date=(v,zone)=>new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short',...(zone?{timeZone:zone}:{})}).format(new Date(v))
const facts=rows=>'<dl class="facts">'+rows.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')+'</dl>'
const STORAGE='atrium.resident.consent-check.v1'

export function mountResidentConsentClient(){
  const root=document.getElementById('consent-root'),el=id=>document.getElementById(id),boot=window.ATRIUM_RESIDENT_CONSENT
  if(!root)return
  let binding,formToken=null,page=null,detail=null,selected=null,busy=false,retired=false,generation=0,draft=null,pending=null,stale=false,timer=null,historyPage=null,listHtml=''
  const controllers=new Set()
  const notice=(message,error=false)=>{el('consent-notice').textContent=message;el('consent-notice').dataset.error=String(error)}
  function close(){draft=null;el('consent-task').innerHTML='';el('consent-task').hidden=true}
  function controls(){root.querySelectorAll('button').forEach(n=>{n.disabled=retired||busy||Boolean(pending)&&!['check','dismiss-check'].includes(n.dataset.consent)||n.dataset.consent==='grant'&&stale});el('consent-refresh').disabled=retired||busy||Boolean(pending)}
  function marker(value){pending=value;try{if(value)sessionStorage.setItem(STORAGE,JSON.stringify({commandId:value.commandId,requestId:value.requestId,purpose:value.purpose}));else sessionStorage.removeItem(STORAGE)}catch{notice('Keep this page open until the saved decision has been checked. This browser could not keep its non-private reference.',true)}}
  function recovery(message='Your decision may have been saved. Check its receipt before making another decision.'){
    el('consent-recovery').hidden=!pending
    if(pending)el('consent-recovery').innerHTML=`<h2>Check your decision</h2><p>${esc(message)}</p><div class="actions"><button type="button" data-consent="check">Check saved decision</button><button type="button" class="secondary" data-consent="dismiss-check">Dismiss after checking with the property team</button></div>`
    else el('consent-recovery').innerHTML=''
  }
  function retire(message,mfa=false){retired=true;generation++;controllers.forEach(c=>c.abort());clearTimeout(timer);detail=null;page=null;historyPage=null;formToken=null;close();el('consent-list').innerHTML='';el('consent-detail').innerHTML='';el('consent-help').innerHTML='';el('consent-recovery').hidden=false;el('consent-recovery').innerHTML=`<h2>Reload your resident review</h2><p>${esc(message)}</p><div class="actions">${mfa?'<a class="button" href="/api/resident?resource=mfa">Verify resident passkey</a>':''}<a class="button" href="/api/resident-consent">Reload reviews</a><a class="button secondary" href="/api/resident?reauthenticate=1">Sign in to resident access</a></div>`;notice(message,true);controls();el('consent-recovery').focus()}
  try{if(!object(boot)||boot.audience!=='resident'||!id(boot.userId)||!uuid(boot.sessionId)||!(boot.requestId===null||uuid(boot.requestId))||!text(boot.formToken,4096))throw new Unconfirmed();binding=Object.freeze({userId:boot.userId,sessionId:boot.sessionId});selected=boot.requestId;formToken=boot.formToken;try{const m=JSON.parse(sessionStorage.getItem(STORAGE)||'null');if(object(m)&&Object.keys(m).length===3&&uuid(m.commandId)&&uuid(m.requestId)&&purpose(m.purpose))pending=m;else sessionStorage.removeItem(STORAGE)}catch{}}catch{retire('This page could not be verified. Sign in and reload.');return}
  function identity(v,action){if(!object(v)||v.audience!=='resident'||v.userId!==binding.userId||v.sessionId!==binding.sessionId||v.action!==action)throw new Unconfirmed();if(v.formToken!==undefined){if(!text(v.formToken,4096))throw new Unconfirmed();formToken=v.formToken}return v}
  async function api(resource,command,extra={}){
    const c=new AbortController(),timeout=setTimeout(()=>c.abort(),15000);controllers.add(c)
    const headers={'x-atrium-user-id':binding.userId,'x-atrium-session-id':binding.sessionId};let url='/api/resident-consent?format=json&resource='+resource
    for(const[k,v]of Object.entries(extra))if(v!==null&&v!==undefined)url+='&'+encodeURIComponent(k)+'='+encodeURIComponent(v)
    if(command){url='/api/resident-consent';Object.assign(headers,{'Content-Type':'application/json','x-atrium-consent-form':formToken,'x-atrium-consent-action':command.action})}
    try{const r=await fetch(url,{method:command?'POST':'GET',headers,credentials:'same-origin',redirect:'error',cache:'no-store',signal:c.signal,...(command?{body:JSON.stringify(command)}:{})});let v;try{v=await r.json()}catch{throw new Unconfirmed()}if(!r.ok)throw new Rejected(object(v)?v.code:null,r.status);return v}finally{controllers.delete(c);clearTimeout(timeout)}
  }
  function helpHtml(help){if(!help)return'<div class="panel warning"><h2>Need help?</h2><p>The property’s supported help route is not configured. Contact your property team through its existing contact method. Online permission remains held where required.</p></div>';return`<div class="panel"><h2>${esc(help.label)}</h2><p>For questions, accessibility assistance or a change to the proposed work, contact your property team. No message is sent by this page.</p><div class="actions"><a class="button secondary" href="tel:${esc(help.phone.replace(/[ ()-]/g,''))}">Call ${esc(help.phone)}</a>${help.url?`<a class="link" href="${esc(help.url)}" target="_blank" rel="noopener noreferrer">Open property help</a>`:''}</div><p class="pre">${esc(help.emergencyInstructions)}</p></div>`}
  function termsHtml(t){return `<h2 class="consent-review-heading" tabindex="-1">${esc(t.publicSummary)}</h2><p class="consent-summary">${esc(t.propertyName)} · Apartment ${esc(t.unitId)}</p><div class="pre">${esc(t.scopeOfWork)}</div>`+facts([['Who would do the work',t.party.name],['Property spending limit',money(t.propertyMaximumCents)+' including all charges'],['Your charge for this job',money(t.residentChargeCents)],['Reviewed payment terms',t.noChargeStatement],['Apartment entry',t.accessRequirement==='no_unit_entry'?'Not required for this work':'Separate permission required']])+ (t.conditions?`<h3>Conditions</h3><p class="consent-conditions">${esc(t.conditions)}</p>`:'')+(t.entryWindow?'<h3>Proposed entry window</h3>'+facts([['Start',date(t.entryWindow.startsAt,t.entryWindow.timeZone)+' · '+t.entryWindow.startsLocal],['End',date(t.entryWindow.endsAt,t.entryWindow.timeZone)+' · '+t.entryWindow.endsLocal],['Timezone',t.entryWindow.timeZone]])+'<p>This window is proposed. No appointment has been confirmed.</p>':'')}
  function renderList(){if(!page)return;const html=`<div class="panel"><h2>Your reviews</h2><p class="hint">Work and entry appear separately. These are the requests currently available to your account.</p><div class="consent-list">${page.items.length?page.items.map(r=>`<button type="button" class="consent-item" data-consent="select" data-id="${esc(r.requestId)}" aria-current="${r.requestId===selected}"><strong>${esc(r.publicSummary)}</strong><span>${esc(r.propertyName)} · ${esc(r.unitId)}</span><span class="badge">${r.purpose==='work'?'Work approval':'Entry permission'} · ${r.effective?'Recorded and effective':r.ownDecision==='decline'?'You declined':r.ownDecision==='revoke'?'You revoked':r.currentTerms?'Review status':'Earlier terms'}</span></button>`).join(''):'<p>No maintenance reviews are listed for this account.</p>'}</div>${page.nextCursor?'<button type="button" class="secondary" data-consent="more">Load more reviews</button>':''}</div>`;if(html!==listHtml){const container=el('consent-list'),scroll=container.querySelector('.consent-list')?.scrollTop||0;container.innerHTML=html;const list=container.querySelector('.consent-list');if(list)list.scrollTop=scroll;listHtml=html}el('consent-list').setAttribute('aria-busy','false');controls()}
  function renderDetail(){if(!detail){el('consent-detail').innerHTML='';return}const d=detail,own=d.ownDecision;el('consent-detail').innerHTML=`<article class="panel consent-section">${termsHtml(d.terms)}<span class="badge">${d.purpose==='work'?'Work approval':'Apartment entry permission'} · ${d.currentTerms?'Current reviewed terms':'Historical terms'}</span><div class="consent-current"><p class="consent-status">${!d.effectiveness.required?'Not required':d.effectiveness.effective?'Required permissions are recorded':own?.decision==='grant'?'Your approval is recorded; current readiness is separate':own?.decision==='decline'?'You declined':own?.decision==='revoke'?'You revoked your permission':'Your decision is pending'}</p>${d.effectiveness.holds.map(h=>`<p>${esc(HOLDS[h])}</p>`).join('')}${stale?'<p class="warning">This status needs refreshing before a new approval.</p>':''}</div>${facts([['Respond by',date(d.responseDeadline)],['Permission ends',date(d.consentValidUntil)],['Last checked',date(d.effectiveness.evaluatedAt)]])}<div class="consent-choice"><h3>${d.purpose==='work'?'Decide about this work':'Decide about this entry window'}</h3><p>${d.purpose==='work'?'Approving this work does not grant apartment entry.':'This permission is only for the named party, purpose and exact window shown above.'}</p><div class="actions">${d.canGrant?`<button type="button" data-consent="grant">${own?'Reconsider and approve with passkey':'Review approval'}</button>`:''}${d.canDecline?'<button type="button" class="secondary" data-consent="decline">Review decline</button>':''}${d.canRevoke?'<button type="button" class="danger" data-consent="revoke">Revoke this permission</button>':''}</div>${d.requiresPasskey&&d.canGrant?'<p class="hint">Approval needs your own active passkey for these exact terms. <a href="/api/resident?resource=mfa">Set up or manage resident passkeys</a>. If you cannot use a passkey, use the property help route; staff cannot approve as you.</p>':''}</div><div class="actions"><button type="button" class="secondary" data-consent="history">View your decision history</button></div><section id="consent-history"></section></article>`;el('consent-help').innerHTML=helpHtml(d.help);renderHistory();controls()}
  function renderHistory(){const target=el('consent-history');if(!historyPage){target.innerHTML='';return}target.innerHTML='<h3 tabindex="-1">Your recorded history</h3><p class="hint">Earlier decisions do not establish current permission.</p><ul class="list">'+historyPage.items.map(h=>`<li><strong>${esc({published:'Terms published',withdrawn:'Review withdrawn',grant:'You approved',decline:'You declined',revoke:'You revoked'}[h.kind])}</strong><p>${esc(date(h.createdAt))} · ${esc(h.purpose==='work'?'Work':'Entry')} · Review ${h.requestVersion}</p><details class="consent-history"><summary>View recorded terms</summary>${termsHtml(h.terms)}</details></li>`).join('')+'</ul>'+(historyPage.nextCursor?'<button type="button" class="secondary" data-consent="history-more">Load earlier history</button>':'');controls()}
  function expireReview(){stale=true;page=null;detail=null;historyPage=null;listHtml='';close();el('consent-list').innerHTML='<div class="panel warning"><h2>Refresh your review status</h2><p>The earliest review deadline was reached. Refresh to check current requests before making a decision.</p></div>';el('consent-detail').innerHTML='';notice('The review status reached its refresh deadline. Refresh before continuing.',true);controls()}
  function arm(){clearTimeout(timer);const boundaries=[page?.refreshAt,detail?.effectiveness.refreshAt,detail?.canGrant?detail.responseDeadline:null,detail?.canGrant?detail.consentValidUntil:null].filter(Boolean).map(Date.parse);if(!boundaries.length)return;const wait=Math.min(...boundaries)-Date.now();if(wait<=0){expireReview();return}timer=setTimeout(expireReview,Math.min(wait,2147483647))}
  async function load(more=false){if(busy||retired||more&&!page?.nextCursor)return;busy=true;controls();const turn=generation,focusMore=more&&document.activeElement?.dataset?.consent==='more';try{const extra={limit:25};if(more)Object.assign(extra,{beforeCreatedAt:page.nextCursor.createdAt,beforeId:page.nextCursor.id});const result=identity(await api('list',null,extra),'list');if(retired||turn!==generation)return;const next=readPage(result.page);if(more){if(next.items.some(r=>page.items.some(p=>p.requestId===r.requestId)))throw new Unconfirmed();page={...next,refreshAt:[page.refreshAt,next.refreshAt].filter(Boolean).sort((a,b)=>Date.parse(a)-Date.parse(b))[0]||null,items:[...page.items,...next.items]}}else page=next;stale=false;renderList();busy=false;let selection;if(selected)selection=select(selected,false);else if(page.items.length)selection=select(page.items[0].requestId,false);else{detail=null;renderDetail()}const selectedGeneration=generation;if(selection)await selection;if(retired||generation!==selectedGeneration)return;recovery();arm();notice(pending?'An earlier decision needs its saved receipt checked.':'Current review list loaded.');if(focusMore)(el('consent-list').querySelector('[data-consent="more"]')||[...el('consent-list').querySelectorAll('[data-consent="select"]')].at(-1)||el('consent-refresh'))?.focus({preventScroll:true})}catch(e){if(retired||turn!==generation)return;stale=true;if(e instanceof Rejected&&([401,403].includes(e.status)||e.code==='consent_changed'||e.code==='account_changed'))retire(e.message,e.code==='mfa_required');else notice('Your current requests could not be loaded. Refresh to check them; no decision was submitted.',true)}finally{if(!retired&&turn===generation){busy=false;controls()}}}
  async function select(requestId,focus=true){if(busy||retired||pending||!uuid(requestId))return;busy=true;controls();const turn=++generation;close();detail=null;historyPage=null;el('consent-detail').innerHTML='<div class="panel"><h2>Loading reviewed terms</h2></div>';try{const v=identity(await api('detail',null,{requestId}),'detail');if(retired||turn!==generation)return;detail=readDetail(v.detail,binding,requestId);selected=requestId;if(page){page.items=page.items.map(r=>r.requestId!==requestId?r:{...r,requestVersion:detail.requestVersion,purpose:detail.purpose,propertyName:detail.terms.propertyName,unitId:detail.terms.unitId,publicSummary:detail.terms.publicSummary,responseDeadline:detail.responseDeadline,consentValidUntil:detail.consentValidUntil,publishedAt:detail.publishedAt,ownDecision:detail.ownDecision?.decision||null,effective:detail.effectiveness.effective,holds:detail.effectiveness.holds,currentTerms:detail.currentTerms})}stale=false;renderList();renderDetail();arm();if(focus)el('consent-detail').querySelector('h2')?.focus({preventScroll:false})}catch(e){if(retired||turn!==generation)return;detail=null;el('consent-detail').innerHTML='';notice(e instanceof Rejected?e.message:'The exact terms could not be verified. Refresh before continuing.',true);if(e instanceof Rejected&&([401,403].includes(e.status)||e.code==='consent_changed'||e.code==='account_changed'))retire(e.message,e.code==='mfa_required')}finally{if(!retired&&turn===generation){busy=false;controls()}}}
  function open(action){if(busy||retired||pending||!detail||!['grant','decline','revoke'].includes(action)||!detail[{grant:'canGrant',decline:'canDecline',revoke:'canRevoke'}[action]]||action==='grant'&&(stale||Date.parse(detail.responseDeadline)<=Date.now()))return;const d=detail;draft={action,commandId:crypto.randomUUID(),requestId:d.requestId,requestVersion:d.requestVersion,expectedDecisionVersion:d.ownDecisionVersion,purpose:d.purpose,...(action==='revoke'?{grantId:d.ownDecision.id}:{termsDigest:d.termsDigest}),...(action==='grant'?{materialDigest:d.materialDigest}:{})};el('consent-task').innerHTML=`<span class="step">Your ${d.purpose==='work'?'work':'entry'} decision</span><h2>${action==='grant'?'Approve these exact terms?':action==='decline'?'Decline these terms?':'Revoke your recorded permission?'}</h2>${termsHtml(d.terms)}<p>${action==='grant'?'You will verify only this decision with your passkey. No appointment, message or payment is made.':action==='decline'?'Your decline is recorded for this purpose only. Use the help route if the work or entry window needs changing.':'This removes your permission in Atrium. It cannot confirm cancellation of an appointment or work that may already have been arranged; contact the property team.'}</p><div class="actions"><button type="button" data-consent="confirm">${action==='grant'?'Approve with my passkey':action==='decline'?'Record my decline':'Revoke this permission'}</button><button type="button" class="secondary" data-consent="close">Go back</button></div>`;el('consent-task').hidden=false;el('consent-task').focus();controls()}
  function options(v,c){identity(v,'grant_options');if(!uuid(v.challengeId)||!Number.isSafeInteger(v.expiresAt)||v.expiresAt<=Date.now()||v.expiresAt>Date.now()+305000||!object(v.optionsJSON)||!text(v.optionsJSON.challenge,4096)||v.optionsJSON.userVerification!=='required'||!text(v.optionsJSON.rpId,253)||!(location.hostname===v.optionsJSON.rpId||location.hostname.endsWith('.'+v.optionsJSON.rpId))||!Array.isArray(v.optionsJSON.allowCredentials)||!v.optionsJSON.allowCredentials.length||v.optionsJSON.allowCredentials.length>10||v.optionsJSON.allowCredentials.some(x=>!object(x)||x.type!=='public-key'||!text(x.id,4096)))throw new Unconfirmed();if(v.command!==undefined&&JSON.stringify(v.command)!==JSON.stringify(c))throw new Unconfirmed();return v}
  async function confirm(){if(busy||retired||pending||!draft)return;const c=clone(draft),turn=generation;busy=true;controls();close();let sent=false;try{let response;if(c.action==='grant'){const start=options(await api('',{action:'grant_options',command:c}),c);if(retired||turn!==generation)return;const assertion=await startAuthentication({optionsJSON:start.optionsJSON});if(retired||turn!==generation)return;if(stale||Date.now()>=start.expiresAt)throw new Unconfirmed();marker(c);sent=true;response=identity(await api('',{action:'grant_finish',challengeId:start.challengeId,response:assertion}),'grant_finish')}else{marker(c);sent=true;response=identity(await api('',c),c.action)}if(retired||turn!==generation)return;const r=readReceipt(response.receipt,binding,c);if(!r)throw new Unconfirmed();marker(null);recovery();busy=false;const refresh=select(c.requestId,false),refreshGeneration=generation;await refresh;if(retired||generation!==refreshGeneration)return;notice('Your '+(c.action==='grant'?'approval':c.action==='decline'?'decline':'revocation')+' was recorded. '+(detail&&!stale?'Current permission is shown separately.':'Refresh to check current permission; it could not be loaded.')+' No appointment or dispatch is confirmed.')}catch(e){if(retired||turn!==generation)return;if(sent){recovery('Your decision may have been saved. Check the exact receipt before making another decision.');notice('The saved result could not be confirmed.',true);if(e instanceof Rejected&&([401,403].includes(e.status)||e.code==='consent_changed'||e.code==='account_changed'))retire('Your decision may have been saved and your sign-in or access ended. Sign in, then check the saved receipt before making another decision.')}else{notice(e?.name==='NotAllowedError'||e?.name==='AbortError'?'Passkey verification was cancelled or timed out. No decision was submitted. Review the terms before trying again.':e instanceof Rejected?e.message:'Passkey verification could not be started or verified. No decision was submitted. Refresh and review before trying again.',true);if(e instanceof Rejected&&([401,403].includes(e.status)||e.code==='consent_changed'||e.code==='account_changed'))retire(e.message,e.code==='mfa_required')}}finally{if(!retired&&turn===generation){busy=false;controls()}}}
  async function check(){if(busy||retired||!pending)return;busy=true;controls();const saved=clone(pending),turn=generation;try{const v=identity(await api('receipt',null,{commandId:saved.commandId}),'receipt');if(retired||turn!==generation)return;const r=readReceipt(v.receipt,binding,saved);if(!r){recovery('No receipt is available yet. That does not prove the decision was not saved. Check again or contact the property team.');return}marker(null);recovery();busy=false;const refresh=select(r.requestId,false),refreshGeneration=generation;await refresh;if(retired||generation!==refreshGeneration)return;notice('Saved '+({grant:'approval',decline:'decline',revoke:'revocation'}[r.action])+' confirmed. '+(detail&&!stale?'Check the current terms and permission status separately.':'Refresh to check current terms; they could not be loaded.'))}catch(e){if(retired||turn!==generation)return;notice('The saved decision could not be checked. Its reference has been kept.',true);if(e instanceof Rejected&&([401,403].includes(e.status)||e.code==='consent_changed'||e.code==='account_changed'))retire('Sign in again to check the earlier decision. It may have been saved.')}finally{if(!retired&&turn===generation){busy=false;controls()}}}
  async function history(more=false){if(busy||retired||!detail||more&&!historyPage?.nextCursor)return;busy=true;controls();const turn=generation,id=detail.requestId,extra={requestId:id,limit:25};if(more)Object.assign(extra,{beforeCreatedAt:historyPage.nextCursor.createdAt,beforeId:historyPage.nextCursor.id});try{const v=identity(await api('history',null,extra),'history'),h=v.history;if(retired||turn!==generation)return;if(!object(h)||!Array.isArray(h.items)||h.items.length>50)throw new Unconfirmed();const items=h.items.map(r=>{if(!object(r)||!uuid(r.id)||r.requestId!==id||!positive(r.requestVersion)||r.purpose!==detail.purpose||!['published','withdrawn','grant','decline','revoke'].includes(r.kind)||!iso(r.createdAt)||!digest(r.termsDigest))throw new Unconfirmed();return {...clone(r),terms:readTerms(r.terms),decision:readDecision(r.decision,binding,{requestId:id,purpose:detail.purpose})}});if(new Set(items.map(r=>r.id)).size!==items.length||more&&items.some(r=>historyPage.items.some(p=>p.id===r.id)))throw new Unconfirmed();historyPage={items:more?[...historyPage.items,...items]:items,nextCursor:readCursor(h.nextCursor)};renderHistory();if(more)(el('consent-history').querySelector('[data-consent="history-more"]')||el('consent-history').querySelector('h3'))?.focus({preventScroll:true})}catch(e){if(!retired&&turn===generation){if(e instanceof Rejected&&([401,403].includes(e.status)||e.code==='consent_changed'||e.code==='account_changed'))retire(e.message,e.code==='mfa_required');else notice('Your earlier decisions could not be loaded. Try again; current permission has not changed.',true)}}finally{if(!retired&&turn===generation){busy=false;controls()}}}
  root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const a=b.dataset.consent;if(b.id==='consent-refresh')void load();else if(a==='select')void select(b.dataset.id);else if(a==='more')void load(true);else if(['grant','decline','revoke'].includes(a))open(a);else if(a==='confirm')void confirm();else if(a==='close')close();else if(a==='check')void check();else if(a==='dismiss-check'&&!busy){marker(null);recovery();void load()}else if(a==='history'||a==='history-more')void history(a==='history-more')})
  window.addEventListener('pagehide',()=>{retired=true;generation++;controllers.forEach(c=>c.abort());clearTimeout(timer);page=null;detail=null;historyPage=null;formToken=null;close();for(const id of ['consent-list','consent-detail','consent-help','consent-recovery'])el(id).innerHTML=''})
  window.addEventListener('pageshow',event=>{if(event.persisted)location.reload()})
  void load()
}
mountResidentConsentClient()
