import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { runInNewContext } from 'node:vm'
const app = await readFile(new URL('../../ops/src/app.js', import.meta.url), 'utf8')
const source = await readFile(new URL('../../ops/src/maintenance-plans.js', import.meta.url), 'utf8')
const serviceSource = await readFile(new URL('../../ops/src/services.js', import.meta.url), 'utf8')
const html = await readFile(new URL('../../ops/src/index.html', import.meta.url), 'utf8')
const css = await readFile(new URL('../../ops/src/maintenance-plans.css', import.meta.url), 'utf8')
const plain = v => JSON.parse(JSON.stringify(v)), settle = async () => { for(let i=0;i<100;i++) await Promise.resolve() }
const result = (body,status=200) => ({ok:status>=200&&status<300,status,json:async()=>body})
const at='2026-09-13T01:00:00.000Z', prior='2026-09-01T14:00:00.123Z', until='2026-10-01T14:00:00.000Z'
const ownership={organizationId:'organization-one',propertyId:'building-one'}
const policy=(overrides={})=>({...ownership,version:2,currency:'USD',automaticLimitCents:null,managerLimitCents:50000,ownerLimitCents:100000,automaticCategories:[],excludedCategories:[],requireResidentApproval:true,requireIndependentApprover:true,sourceReference:'Synthetic owner rules',observedAt:prior,validUntil:until,publishedBy:'owner-one',publishedAt:prior,...overrides})
const vendor=(overrides={})=>({...ownership,id:'vendor-one',version:3,name:'Example Plumbing',categories:['plumbing'],status:'approved',phone:'+13125550199',email:null,serviceArea:'This property',hours:'Weekdays 9–5',emergencyCoverage:false,availability:'unknown',availabilityObservedAt:null,availabilityValidUntil:null,expectedPricing:'Quote required',responseTargetMinutes:null,preference:0,restrictions:'',sourceReference:'Synthetic approved directory',observedAt:prior,validUntil:until,reviewedBy:'owner-one',reviewedAt:prior,createdAt:prior,...overrides})
const request=(overrides={})=>({...ownership,id:'case-one',version:4,summary:'Repair common-area tap',category:'plumbing',priority:'routine',state:'ready_for_planning',contextNeedsReview:false,emergencyKinds:[],location:{kind:'common_area',label:'Lobby'},...overrides})
const plan=(overrides={})=>({...ownership,id:'plan-one',caseId:'case-one',version:2,caseVersion:4,configurationVersion:3,residentId:null,residentVersion:null,policyVersion:2,preparedBy:'staff-one',preparedAt:prior,createdAt:prior,withdrawnAt:null,emergencyKinds:[],route:'internal',vendorId:null,vendorVersion:null,internalTeam:'Building maintenance',scopeOfWork:'Replace the worn tap washer',currency:'USD',maximumCents:25000,includesAllCharges:true,accessRequirement:'no_unit_entry',restrictions:[],reason:'Reviewed routine repair',...overrides})
const assessment=(overrides={})=>({tier:'approval_required',readiness:'awaiting_manager',reasons:['A currently authorized manager or owner must approve this exact plan.'],requiredApprover:'admin_or_owner',spendingAuthorized:false,residentApprovalRequired:true,residentApprovalVerified:false,entryAuthorized:false,dispatchStatus:'not_dispatched',notificationStatus:'not_sent',...overrides})
const history=(overrides={})=>({id:'history-one',planId:'plan-one',planVersion:2,kind:'prepared',actorUserId:'staff-one',createdAt:prior,reason:'Reviewed routine repair',scopeOfWork:'Replace the worn tap washer',maximumCents:25000,currency:'USD',vendorName:null,policyVersion:2,caseVersion:4,...overrides})
const detail=(overrides={})=>({request:request(),resident:{state:'not_established',residentId:null,residentVersion:null,displayName:null,unitId:null,callerIdentityVerified:false,entryAuthorized:false},policy:policy(),plan:plan(),vendor:null,decision:null,assessment:assessment(),canDecide:true,history:[history()],nextHistoryCursor:null,...overrides})
function portal({legacy=false,permissions=['read','operate','configure'],role='owner',mobile=false,reduced=false}={}){
 const scope={...ownership,configurationVersion:3,permissionVersion:'permission-three'},requests=[],dialogs=[],toasts=[],timers=new Map(),listeners=new Map()
 let uuid=0,timerId=0,reloads=0,active=true,handler=defaultHandler,service=null,clock=Date.parse(at)
 const document={readyState:'loading',activeElement:null,addEventListener(){},getElementById(){return null},querySelector(){return null},querySelectorAll:key=>key==='.view'?[host]:[],body:{classList:{toggle(){},add(){},remove(){}}}}
 const camel=k=>k.replace(/-([a-z])/g,(_,c)=>c.toUpperCase())
 function node(){let content='',children=[];const n={dataset:{},attributes:{},value:'',checked:false,disabled:false,hidden:false,isConnected:true,scrollTop:0,scrollLeft:0,writes:0,handlers:new Map(),classList:{add(){},remove(){},toggle(){}},
   setAttribute(k,v){n.attributes[k]=String(v)},getAttribute(k){return n.attributes[k]},removeAttribute(k){delete n.attributes[k]},addEventListener(k,f){n.handlers.set(k,f)},focus(){document.activeElement=n},scrollIntoView(v){n.scrolled=v},contains(v){return v===n||children.some(c=>c.contains(v))},
   matches(selector){if(selector==='button')return n.tagName==='BUTTON';if(selector.startsWith('#'))return n.id===selector.slice(1);if(selector.startsWith('.'))return(n.attributes.class||'').split(' ').includes(selector.slice(1));const m=/^\[data-([\w-]+)(?:="([^"]+)")?\]$/.exec(selector);return !!m&&Object.hasOwn(n.dataset,camel(m[1]))&&(m[2]===undefined||n.dataset[camel(m[1])]===m[2])},
   closest(selector){return selector.split(',').some(v=>n.matches(v.trim()))?n:null},querySelectorAll(selector){return [...children.filter(c=>selector.split(',').some(v=>c.matches(v.trim()))),...children.flatMap(c=>c.querySelectorAll(selector))]},querySelector(selector){return n.querySelectorAll(selector)[0]||null},get childNodes(){return children},replaceChildren(...next){children=next;if(!next.length)content=''},insertAdjacentHTML(_,value){n.innerHTML=content+value},
   get innerHTML(){return content},set innerHTML(value){content=value;n.writes++;children.forEach(c=>{c.isConnected=false});children=[...value.matchAll(/<(button|a|h2|h3|h4|input|select|textarea|div|p|section|details|summary|fieldset)\b([^>]*)>/g)].map(match=>{const [,tag,attrs]=match,c=node();c.tagName=tag.toUpperCase();for(const [,key,v]of attrs.matchAll(/([\w-]+)="([^"]*)"/g)){c.attributes[key]=v;if(key.startsWith('data-'))c.dataset[camel(key.slice(5))]=v;if(key==='id')c.id=v;if(key==='value')c.value=v}for(const [,key]of attrs.matchAll(/\s(data-[\w-]+)(?=\s|$)/g))c.dataset[camel(key.slice(5))]='';c.checked=/\schecked(?:\s|$)/.test(attrs);c.disabled=/\sdisabled(?:\s|$)/.test(attrs);c.hidden=/\shidden(?:\s|$)/.test(attrs);if(tag==='select'){const inner=value.slice(match.index+match[0].length).split('</select>')[0],options=[...inner.matchAll(/<option\b([^>]*)>/g)],s=options.find(o=>/\sselected(?:\s|$)/.test(o[1]))||options[0];c.value=s?/value="([^"]*)"/.exec(s[1])?.[1]||'':''}if(tag==='textarea')c.value=value.slice(match.index+match[0].length).split('</textarea>')[0];return c})}
 };return n}
 const host=node(),notice=node(),location={hash:'#/services',pathname:'/api/dashboard',reload(){reloads++}}
 const window={ATRIUM_RUNTIME_MODE:legacy?'legacy':'postgres',ATRIUM_PROPERTY:{...scope,buildingName:'Lake House',timeZone:'America/Chicago',permissions,hours:{}},ATRIUM_ACCOUNT:{username:'operator',tenantId:'larkin'},addEventListener(k,f){if(!listeners.has(k))listeners.set(k,[]);listeners.get(k).push(f)}}
 class FixedDate extends Date{constructor(...args){super(...(args.length?args:[clock]))}static now(){return clock}}
 const context={window,document,location,Date:FixedDate,Intl,URLSearchParams,structuredClone,console,crypto:{randomUUID(){return'00000000-0000-4000-8000-'+String(++uuid).padStart(12,'0')}},matchMedia:q=>({matches:q.includes('reduced-motion')?reduced:mobile}),setTimeout(fn,delay){const id=++timerId;timers.set(id,{fn,delay,fireAt:clock+delay});return id},clearTimeout(id){timers.delete(id)},setInterval(){},clearInterval(){},fetch:async(path,init)=>{requests.push({path,...init});return handler(path,init)}}
 runInNewContext(app.replace('window.Atrium = {','window.planningAppTest = { emit, markBooted() { booted = true }, accessIssue: () => documentAccessIssue }; window.Atrium = {'),context)
 const A=window.Atrium;A.toast=(message,options)=>{const r={message,options,closed:false,close(){r.closed=true}};toasts.push(r);return r};A.announce=()=>{};A.paintPermissions=()=>{}
 A.dialog=options=>{const body=node(),d={body,options,error:null,primary:{...options.primary},closed:false,setError(v){d.error=v},setPrimary(v){Object.assign(d.primary,v)},setBusy(v){d.busy=v},close(){if(!d.closed){d.closed=true;options.onClose?.()}},click(){return options.primary.onClick(d)}};options.build(body,d);dialogs.push(d);return d}
 runInNewContext(source.replace('return Object.freeze({attach,deactivate,locked,','return Object.freeze({_test: { open, load, chooseVendor, moreHistory, formCommand, formHtml, state: () => ({mode,caseId,overview,detail,vendors,vendor,loading,error,pending,busy}) },attach,deactivate,locked,').replace('A.maintenancePlans=Object.freeze({create,inbox:', 'window.planningTest={readDetail,readPolicy,readVendor,readHistory,readReceipt,dollars,sourceInstant,availability,readInboxPage}; A.maintenancePlans=Object.freeze({create,inbox:'),context)
 const controller=A.maintenancePlans?.create({isActive:()=>active&&A.can('operate'),canOpen:()=>true,onChange(){}});controller?.setNotice(notice)
 const body=v=>({scope,...v}), receipt=(command,changes={})=>({requestId:command.requestId,action:command.action,resource:command.action==='publish_policy'?'policy':command.action==='save_vendor'?'vendor':'plan',id:command.action==='publish_policy'?scope.propertyId:command.action==='save_vendor'?command.id||'vendor-new':command.planId||'plan-one',version:command.action==='decide_plan'?command.expectedPlanVersion:(command.expectedVersion??command.expectedPlanVersion)+1,committedAt:at,replayed:false,outcome:'saved',...changes})
 function defaultHandler(path,init){const q=new URL(path,'https://example.test').searchParams;if(init?.method==='POST'){const c=JSON.parse(init.body);return result(body({receipt:receipt(c)}))}if(q.get('resource')==='overview')return result(body({policy:policy(),actorRole:role,canPublishPolicy:role==='owner',canManageVendors:permissions.includes('configure'),formToken:'planning-synthetic-token'}));if(q.get('resource')==='plan')return result(body({detail:detail({request:request({id:q.get('caseId')}),plan:plan({caseId:q.get('caseId')})}),safetyInstructions:[],safetyCallEmergencyServices:false}));if(q.get('resource')==='vendors')return result(body({vendors:[vendor()],nextCursor:null}));if(q.get('resource')==='vendor')return result(body({vendor:vendor({id:q.get('id')})}));if(q.get('resource')==='history')return result(body({history:[],nextCursor:null}))}
 return {A,controller,helpers:window.planningTest,host,notice,document,window,context,location,requests,dialogs,toasts,scope,body,receipt,node,defaultHandler,setHandler(fn){handler=fn},async mount(mode='case'){controller?.attach(host,mode==='case'?{mode,request:request()}:{mode});await settle()},async expire(){for(const [id,t]of timers)if(t.delay===15000){timers.delete(id);t.fn()}await settle()},async advance(ms){clock+=ms;for(const [id,t]of [...timers])if(t.fireAt<=clock){timers.delete(id);t.fn()}await settle()},closeView(clear=false){active=false;controller?.deactivate(clear)},activate(){active=true},reloads:()=>reloads,click(selector,inNotice=false){const h=inNotice?notice:host,b=h.querySelector(selector);assert.ok(b,selector);h.handlers.get('click')({target:b,preventDefault(){}});return b},markBooted(){window.planningAppTest.markBooted()},
  mountService(){runInNewContext(serviceSource.replace("A.register('services', view)","window.planningServiceTest = {view,paint,openForm,load,loadInbox,select,state:()=>({tab,planning,items,cursor,selected,detail,error,loading,inboxScan,inboxExpired})}; A.register('services', view)"),context);service=window.planningServiceTest;return service},emitPage(name,event={}){for(const fn of listeners.get(name)||[])fn(event)}}
}
const fill=(d,values)=>{for(const [key,value]of Object.entries(values)){const n=d.body.querySelector('#mp-'+key);assert.ok(n,key);if(typeof value==='boolean')n.checked=value;else n.value=value}}
const prepareValues={scope:'Replace the worn tap washer',route:'internal',team:'Building maintenance',maximum:'250.00','all-charges':true,entry:'no_unit_entry',reason:'Reviewed routine repair'}
const inboxItem=(overrides={})=>({id:'case-one',caseVersion:4,summary:'Repair common-area tap',location:{kind:'common_area',label:'Lobby'},category:'plumbing',priority:'routine',createdAt:prior,updatedAt:prior,planId:'plan-one',planVersion:2,planPreparedAt:prior,maximumCents:25000,includesAllCharges:true,currency:'USD',assessment:assessment(),canDecide:true,group:'attention',nextStep:{kind:'review_decision',label:'Review the exact plan for a decision',responsible:'manager_or_owner',availableInPortal:true},...overrides})
const inboxPage=(items=[inboxItem()],overrides={})=>({items,nextCursor:null,evaluatedAt:at,scanStartedAt:at,scanExpiresAt:'2026-09-13T01:05:00.000Z',scannedCount:items.length,scanIncomplete:false,...overrides})
async function inboxPortal(options={},pageHandler=null){
 const ui=portal(options),service=ui.mountService()
 const fullCase=id=>({...request({id}),requestOrigin:'staff_observation',description:'Drips after closing',reportedPriority:'routine',reporterName:null,reporterPhone:null,reporterEmail:null,accessNotes:'',createdAt:prior,updatedAt:prior,createdBy:'staff-one',residentId:null,intakeLocation:{kind:'common_area',label:'Lobby'},residentIdAtIntake:null,residentVersionAtIntake:null,residentNameAtIntake:null,callerIdentityVerified:false,entryAuthorized:false,dispatchStatus:'not_dispatched',notificationStatus:'not_sent'})
 const baseline=(path,init)=>{const q=new URL(path,'https://example.test').searchParams
  if(path.startsWith('/api/maintenance-plans'))return q.get('resource')==='inbox'?pageHandler?pageHandler(q,ui):result(ui.body(inboxPage())):ui.defaultHandler(path,init)
  if(q.get('resource')==='overview')return result(ui.body({canManageResidents:true,timeZone:'America/Chicago',units:[{id:'13L',label:'13L'}],formToken:'service-token'}))
  if(q.get('resource')==='request')return result(ui.body({detail:{request:fullCase(q.get('id')),resident:detail().resident,events:[],eventsTruncated:false,nextEventsCursor:null,related:[],relatedTruncated:false},safetyInstructions:[],safetyCallEmergencyServices:false}))
  if(q.get('resource')==='requests')return result(ui.body({requests:[fullCase('case-one')],nextCursor:null}))
  return result({},404)
 }
 ui.setHandler(baseline);ui.A.navigate=(name,params={})=>{ui.location.hash=ui.A.hashFor(name,params);service.view.render();ui.window.planningAppTest.emit('route',ui.A.route())}
 ui.location.hash=ui.A.hashFor('services',{tab:'plans'});service.view.mount(ui.host);service.view.render();await settle()
 return {...ui,service,baseline,clickService(selector){const b=ui.host.querySelector(selector);assert.ok(b,selector);ui.host.handlers.get('click')({target:b,preventDefault(){}});return b}}
}
test('inbox tab loads current case and plan detail before exposing existing decisions',async()=>{
 const ui=await inboxPortal();assert.equal(ui.service.state().tab,'plans');assert.equal(ui.service.state().detail.request.id,'case-one');assert.equal(ui.host.querySelector('.sv-story').hidden,true)
 assert.ok(ui.requests.some(r=>r.path.includes('resource=request&id=case-one')));assert.ok(ui.requests.some(r=>r.path.includes('resource=plan&caseId=case-one')))
 assert.match(ui.host.querySelector('.sv-results').innerHTML,/Manager approval needed/);assert.doesNotMatch(ui.host.querySelector('.sv-results').innerHTML,/data-mp="approve"/)
 assert.match(ui.host.querySelector('.sv-planning-case').innerHTML,/data-mp="approve"/);assert.equal(ui.host.querySelector('[data-command="add"]').hidden,true)
 assert.match(ui.host.querySelector('.sv-loaded').textContent,/Pages are checked as loaded/)
 ui.A.navigate('services',{state:'planning'});await settle();assert.equal(ui.service.state().detail.request.id,'case-one','existing Requests initial detail still loads');assert.equal(ui.host.querySelector('.sv-story').hidden,false)
})
test('sparse zero-match pages continue checking through the opaque cursor without claiming empty',async()=>{
 const ui=await inboxPortal({},(q,u)=>result(u.body(q.has('cursor')?inboxPage([inboxItem()],{scannedCount:3}):inboxPage([],{nextCursor:'opaque-page-two',scannedCount:200,scanIncomplete:true}))))
 assert.match(ui.host.querySelector('.sv-results').innerHTML,/More requests to check/);assert.equal(ui.host.querySelector('[data-command="more"]').textContent,'Continue checking');assert.equal(ui.service.state().detail,null)
 const more=ui.host.querySelector('[data-command="more"]');more.focus();ui.clickService('[data-command="more"]');await settle()
 assert.equal(ui.service.state().items.length,1);assert.equal(ui.service.state().inboxScan.totalScanned,203);assert.equal(ui.document.activeElement.dataset.select,'case-one')
 assert.ok(ui.requests.some(r=>r.path.includes('cursor=opaque-page-two')));assert.equal(ui.host.querySelector('[data-command="more"]').hidden,true)
})
test('waiting and all filters preserve truthful authorization, unknown cost and zero ceilings',async()=>{
 const waiting=inboxItem({group:'waiting',maximumCents:null,canDecide:false,assessment:assessment({readiness:'authorized_plan',spendingAuthorized:true}),nextStep:{kind:'arrange_work',label:'Arrange and verify the work appointment',responsible:'property_team',availableInPortal:false}})
 const ui=await inboxPortal({},(q,u)=>result(u.body(inboxPage(q.get('filter')==='waiting'?[waiting]:[inboxItem({maximumCents:0})]))))
 assert.match(ui.host.querySelector('.sv-results').innerHTML,/\$0\.00 ceiling/);ui.clickService('[data-filter="waiting"]');await settle()
 assert.match(ui.host.querySelector('.sv-results').innerHTML,/Cost not established/);assert.match(ui.host.querySelector('.sv-results').innerHTML,/Authorized plan — not dispatched/)
 ui.clickService('[data-filter="all"]');await settle();assert.equal(new URL(ui.requests.findLast(r=>r.path.includes('resource=inbox')).path,'https://example.test').searchParams.get('filter'),'all')
})
test('inbox refuses bad projection, invented authority, group mismatch and cross-page scan mixing',()=>{
 const read=portal().helpers.readInboxPage
 for(const mutate of [p=>{p.items[0].assessment.entryAuthorized=true},p=>{p.items[0].group='waiting'},p=>{p.items[0].maximumCents=-1},p=>{p.items[0].nextStep.responsible='anyone'},p=>{p.scannedCount=201},p=>{p.scanIncomplete=true}]){const p=inboxPage();mutate(p);assert.throws(()=>read(p,'attention'),/could not be verified/)}
 assert.throws(()=>read(inboxPage(),'attention','13L'),/could not be verified/)
 assert.throws(()=>read(inboxPage([], {scanStartedAt:'2026-09-13T01:00:01.000Z'}),'attention','',inboxPage()),/could not be verified/)
 const e=inboxItem({canDecide:false,priority:'routine',assessment:assessment({tier:'emergency',readiness:'emergency_review'}),nextStep:{kind:'review_emergency',label:'Review emergency instructions',responsible:'property_team',availableInPortal:true}})
 assert.equal(read(inboxPage([e]),'attention').items[0].assessment.readiness,'emergency_review')
})
test('selection updates preserve list DOM and scroll; mobile selection focuses detail and returns to row',async()=>{
 const ui=await inboxPortal({mobile:true,reduced:true},(q,u)=>result(u.body(inboxPage([inboxItem(),inboxItem({id:'case-two',summary:'Second request'})]))))
 const list=ui.host.querySelector('.sv-results');list.scrollTop=420;const writes=list.writes;ui.clickService('[data-select="case-two"]');await settle()
 assert.equal(list.writes,writes);assert.equal(list.scrollTop,420);assert.equal(ui.service.state().detail.request.id,'case-two')
 assert.equal(ui.document.activeElement.dataset.key,'service-detail-heading');assert.equal(ui.document.activeElement.scrolled.behavior,'auto')
 ui.clickService('[data-command="back-list"]');assert.equal(ui.document.activeElement.dataset.select,'case-two')
 await ui.service.loadInbox();assert.equal(ui.service.state().selected,'case-two');assert.equal(list.scrollTop,420)
})
test('late list responses cannot overwrite a new filter or repopulate a departed Service view',async()=>{
 const ui=await inboxPortal();let resolve
 ui.setHandler((path,init)=>path.includes('resource=inbox')?new Promise(r=>{resolve=r}):ui.baseline(path,init));const old=ui.service.loadInbox();await settle()
 ui.setHandler(ui.baseline);ui.A.navigate('services',{tab:'plans',state:'all'});await settle();resolve(result(ui.body(inboxPage([inboxItem({id:'old-case'})]))));await old
 assert.equal(ui.service.state().items[0].id,'case-one')
 let after;ui.setHandler((path,init)=>path.includes('resource=inbox')?new Promise(r=>{after=r}):ui.baseline(path,init));const pending=ui.service.loadInbox();await settle();ui.emitPage('pagehide');after(result(ui.body(inboxPage())));await pending
 assert.equal(ui.host.innerHTML,'');assert.equal(ui.service.state().items.length,0)
})
test('five-minute expiry removes loaded rows and current detail; refresh starts without old cursor',async()=>{
 const ui=await inboxPortal();const planning=ui.service.state().planning;planning._test.open('prepare_plan');assert.equal(ui.dialogs.at(-1).closed,false)
 await ui.advance(300001);assert.equal(ui.service.state().inboxExpired,true);assert.equal(ui.service.state().items.length,0);assert.equal(ui.service.state().detail,null);assert.equal(ui.dialogs.at(-1).closed,true);assert.match(ui.host.querySelector('.sv-errors').innerHTML,/scan expired/)
 const newAt='2026-09-13T01:05:00.001Z';ui.setHandler((path,init)=>path.includes('resource=inbox')?result(ui.body(inboxPage([inboxItem()],{evaluatedAt:newAt,scanStartedAt:newAt,scanExpiresAt:'2026-09-13T01:10:00.001Z'}))):ui.baseline(path,init))
 ui.clickService('[data-command="refresh"]');await settle();assert.equal(ui.service.state().inboxExpired,false);assert.equal(ui.service.state().detail.request.id,'case-one')
 assert.equal(new URL(ui.requests.findLast(r=>r.path.includes('resource=inbox')).path,'https://example.test').searchParams.has('cursor'),false)
})
test('expired continuation requires a new scan, while read failures leave Refresh usable',async()=>{
 const ui=await inboxPortal({},(q,u)=>q.has('cursor')?result({code:'planning_cursor_expired',error:'Refresh this scan'},409):result(u.body(inboxPage([inboxItem()],{nextCursor:'continue',scannedCount:200,scanIncomplete:true}))))
 ui.clickService('[data-command="more"]');await settle();assert.equal(ui.service.state().items.length,0);assert.match(ui.host.querySelector('.sv-errors').innerHTML,/scan expired/)
 ui.setHandler(()=>result({error:'Unavailable'},503));ui.clickService('[data-command="refresh"]');await settle();assert.equal(ui.host.querySelector('[data-command="refresh"]').disabled,false);assert.match(ui.host.querySelector('.sv-errors').innerHTML,/could not be checked/)
 ui.setHandler(ui.baseline);ui.clickService('[data-command="refresh"]');await settle();assert.equal(ui.service.state().items.length,1)
})
test('a later page can shorten the evidence deadline, never extend it or continue without progress',async()=>{
 const read=portal().helpers.readInboxPage,first=inboxPage([inboxItem()],{nextCursor:'next',scanIncomplete:true,scannedCount:200})
 const shortened=inboxPage([inboxItem({id:'case-two'})],{scanExpiresAt:'2026-09-13T01:01:00.000Z'})
 assert.equal(read(shortened,'attention','',first).scanExpiresAt,shortened.scanExpiresAt)
 assert.throws(()=>read(inboxPage(),'attention','',shortened),/could not be verified/)
 assert.throws(()=>read(inboxPage([],{nextCursor:'no-progress'}),'attention'),/could not be verified/)
 assert.throws(()=>read(inboxPage([],{nextCursor:'x'.repeat(801),scannedCount:1}),'attention'),/could not be verified/)
 const ui=await inboxPortal({},(q,u)=>result(u.body(q.has('cursor')?shortened:first)));ui.clickService('[data-command="more"]');await settle();await ui.advance(60001)
 assert.equal(ui.service.state().inboxExpired,true);assert.equal(ui.service.state().items.length,0)
})
test('an unconfirmed write survives scan expiry with only exact-command recovery available',async()=>{
 const ui=await inboxPortal();const own=ui.service.state().planning;let posts=0
 ui.setHandler((path,init)=>init?.method==='POST'&&++posts===1?result(ui.body({}),200):ui.baseline(path,init));own._test.open('prepare_plan');const d=ui.dialogs.at(-1);fill(d,prepareValues);await d.click();await d.click();assert.equal(own.pending,true)
 await ui.advance(300001);assert.equal(ui.service.state().items.length,0);assert.equal(own.pending,true)
 const notice=ui.host.querySelector('.sv-planning-notice');assert.match(notice.innerHTML,/unconfirmed/);const retry=notice.querySelector('[data-mp="retry"]');notice.handlers.get('click')({target:retry,preventDefault(){}})
 const recovery=ui.dialogs.at(-1);assert.notEqual(recovery,d);await recovery.click();await settle()
 const writes=ui.requests.filter(r=>r.method==='POST');assert.equal(writes.length,2);assert.equal(writes[0].body,writes[1].body);assert.equal(writes[0].headers['x-atrium-planning-form'],writes[1].headers['x-atrium-planning-form']);assert.equal(own.pending,false)
})
test('a saved plan refreshes current inbox membership and explains a removed selection',async()=>{
 const ui=await inboxPortal();let saved=false
 ui.setHandler((path,init)=>{if(init?.method==='POST')saved=true;if(saved&&path.includes('resource=inbox'))return result(ui.body(inboxPage([inboxItem({id:'case-two',summary:'Next request requiring review'})])));return ui.baseline(path,init)})
 const own=ui.service.state().planning;own._test.open('decide_plan','reject');const d=ui.dialogs.at(-1);fill(d,{reason:'Revise the scope and total before approval'});await d.click();await d.click();await settle()
 assert.equal(ui.service.state().selected,'case-two');assert.equal(ui.service.state().detail.request.id,'case-two');assert.match(ui.host.querySelector('.sv-inbox-info').innerHTML,/previously selected request is not in these checked results/)
 assert.equal(ui.requests.filter(r=>r.method==='POST').length,1);assert.equal(ui.requests.filter(r=>r.path.includes('resource=inbox')).length,2)
})
test('a matching list row cannot authorize a decision that fresh detail now refuses',async()=>{
 const ui=await inboxPortal();ui.setHandler((path,init)=>path.includes('resource=plan&')?result(ui.body({detail:detail({canDecide:false,assessment:assessment({readiness:'awaiting_resident',spendingAuthorized:true})}),safetyInstructions:[],safetyCallEmergencyServices:false})):ui.baseline(path,init))
 await ui.service.select('case-one',false);await settle();assert.equal(ui.host.querySelector('.sv-planning-case').querySelector('[data-mp="approve"]'),null)
 assert.match(ui.host.querySelector('.sv-planning-case').innerHTML,/Resident approval not established/);ui.service.state().planning._test.open('decide_plan','approve');assert.equal(ui.dialogs.length,0)
})
test('wrong property echoes retire the inbox and unresolved reads cannot announce successful refresh',async()=>{
 const ui=await inboxPortal();ui.markBooted();ui.setHandler((path,init)=>path.includes('resource=inbox')?result({...inboxPage(),scope:{...ui.scope,propertyId:'foreign'}}):ui.baseline(path,init));await ui.service.loadInbox();assert.equal(ui.host.hidden,true);assert.equal(ui.host.innerHTML,'')
 const waiting=await inboxPortal();let finish;waiting.setHandler((path,init)=>path.includes('resource=inbox')?new Promise(r=>{finish=r}):waiting.baseline(path,init));const round=waiting.service.loadInbox();await settle();await waiting.expire();await round
 assert.equal(waiting.service.state().loading,false);assert.equal(waiting.host.querySelector('[data-command="refresh"]').disabled,false);assert.match(waiting.host.querySelector('.sv-errors').innerHTML,/could not be checked/)
 finish(result(waiting.body(inboxPage([inboxItem({id:'late'})]))));await settle();assert.notEqual(waiting.service.state().selected,'late');assert.equal(waiting.service.state().detail,null)
})
test('planning is managed operate-only and source includes precede Service',async()=>{for(const options of [{legacy:true},{permissions:['read']}]){const ui=portal(options);await ui.mount();assert.equal(ui.controller,undefined);assert.equal(ui.requests.length,0)}assert.ok(html.indexOf('include maintenance-plans.js')<html.indexOf('include services.js'));assert.match(css,/min-height:48px/);assert.match(css,/prefers-reduced-motion/)})
test('actual API transport freezes property and planning action/form headers',async()=>{const ui=portal();ui.window.ATRIUM_PROPERTY.propertyId='tampered';await ui.mount();await ui.A.api.post('/api/maintenance-plans',{action:'prepare_plan'},{formToken:'exact-token'});const h=ui.requests.at(-1).headers;assert.equal(h['x-atrium-property-id'],'building-one');assert.equal(h['x-atrium-planning-form'],'exact-token');assert.equal(h['x-atrium-planning-action'],'prepare_plan')})
test('authority reasons retain server text and plan is not dispatch or resident approval',async()=>{const ui=portal();ui.setHandler((path,init)=>path.includes('resource=plan&')?result(ui.body({detail:detail({assessment:assessment({readiness:'authorized_plan',spendingAuthorized:true,reasons:['This internal plan is authorized. No appointment, dispatch or notification has been made.']})}),safetyInstructions:[],safetyCallEmergencyServices:false})):ui.defaultHandler(path,init));await ui.mount();assert.match(ui.host.innerHTML,/Authorized plan — not dispatched/);assert.doesNotMatch(ui.host.innerHTML,/Review required: This internal/);assert.match(ui.host.innerHTML,/Entry permission and caller identity are not established/);assert.throws(()=>ui.helpers.readDetail({...detail(),assessment:assessment({entryAuthorized:true}),safetyInstructions:[],safetyCallEmergencyServices:false},'case-one'),/could not be verified/)})
test('malformed and wrong-property reads cannot offer decision controls',async()=>{for(const mutate of [d=>{d.plan.propertyId='foreign'},d=>{d.canDecide='true'},d=>{d.plan.emergencyKinds=undefined},d=>{d.decision={id:'decision-one',planId:'plan-one',planVersion:2,decision:'approve',actorUserId:'owner',actorRole:'owner',decidedAt:at,reason:'Approved',authorityCurrent:true}}]){const ui=portal(),d=detail();mutate(d);ui.setHandler((path,init)=>path.includes('resource=plan&')?result(ui.body({detail:d,safetyInstructions:[],safetyCallEmergencyServices:false})):ui.defaultHandler(path,init));await ui.mount();assert.equal(ui.controller._test.state().detail,null);assert.match(ui.host.innerHTML,/could not be verified/)}})
test('first overview failure has a usable retry and does not claim loaded data',async()=>{const ui=portal();ui.setHandler(()=>result({error:'Unavailable'},503));await ui.mount();assert.match(ui.host.innerHTML,/could not be loaded/);const b=ui.host.querySelector('[data-mp="refresh"]');assert.equal(b.disabled,false);ui.setHandler(ui.defaultHandler);ui.click('[data-mp="refresh"]');await settle();assert.ok(ui.controller._test.state().detail)})
test('case change ignores late response; deactivation cannot repopulate protected content',async()=>{const ui=portal();await ui.mount();let release;ui.setHandler(()=>new Promise(resolve=>{release=resolve}));const old=ui.controller.refresh();ui.setHandler(ui.defaultHandler);ui.controller.attach(ui.host,{mode:'case',request:request({id:'case-two'})});await settle();release(result(ui.body({policy:policy(),actorRole:'owner',canPublishPolicy:true,canManageVendors:true,formToken:'old-token'})));await old;assert.equal(ui.controller._test.state().detail.request.id,'case-two');let late;ui.setHandler(()=>new Promise(resolve=>{late=resolve}));const second=ui.controller.refresh();ui.closeView(true);late(result(ui.body({policy:policy(),actorRole:'owner',canPublishPolicy:true,canManageVendors:true,formToken:'late-token'})));await second;assert.equal(ui.controller._test.state().overview,null)})
test('USD parser distinguishes unknown and zero and refuses rounding or exponent bypass',()=>{const h=portal().helpers;assert.equal(h.dollars('','Cost'),null);assert.equal(h.dollars('0','Cost'),0);assert.equal(h.dollars('0.01','Cost'),1);for(const v of ['1e3','0.001','-1','NaN','10000000.01'])assert.throws(()=>h.dollars(v,'Cost'));assert.throws(()=>h.dollars('','Owner',false))})
test('policy starts restrictive and only owner capability exposes publishing',async()=>{const ui=portal();ui.setHandler((path,init)=>path.includes('resource=overview')?result(ui.body({policy:null,actorRole:'owner',canPublishPolicy:true,canManageVendors:true,formToken:'t'})):ui.defaultHandler(path,init));await ui.mount('directory');ui.controller._test.open('publish_policy');const d=ui.dialogs.at(-1);assert.equal(d.body.querySelector('#mp-automatic').value,'');assert.equal(d.body.querySelector('#mp-manager').value,'');assert.equal(d.body.querySelector('#mp-resident-approval').checked,true);assert.equal(d.body.querySelector('#mp-independent').checked,true);await d.click();assert.match(d.error,/Owner ceiling/);assert.equal(ui.requests.filter(r=>r.method==='POST').length,0);const staff=portal({role:'staff',permissions:['read','operate']});await staff.mount('directory');staff.controller._test.open('publish_policy');staff.controller._test.open('save_vendor','new');assert.equal(staff.dialogs.length,0)})
test('plan review freezes whole command, vendor-independent internal route and existing version IDs',async()=>{const ui=portal();await ui.mount();ui.controller._test.open('prepare_plan');const d=ui.dialogs.at(-1);fill(d,prepareValues);await d.click();assert.equal(ui.requests.filter(r=>r.method==='POST').length,0);assert.match(d.body.innerHTML,/\$250\.00/);assert.match(d.body.innerHTML,/Not dispatched|does not dispatch/);await d.click();const c=JSON.parse(ui.requests.find(r=>r.method==='POST').body);assert.equal(c.expectedCaseVersion,4);assert.equal(c.expectedPlanVersion,2);assert.equal(c.policyVersion,2);assert.equal(c.details.vendorId,null);assert.equal(c.details.maximumCents,25000);assert.equal(ui.controller.pending,false)})
test('malformed successful write preserves exact request and body across deliberate retry',async()=>{const ui=portal();await ui.mount();let posted=0;ui.setHandler((path,init)=>init?.method==='POST'?(++posted===1?{ok:true,status:200,json:async()=>{throw new Error('truncated')}}:ui.defaultHandler(path,init)):ui.defaultHandler(path,init));ui.controller._test.open('prepare_plan');const d=ui.dialogs.at(-1);fill(d,prepareValues);await d.click();await d.click();assert.equal(ui.controller.pending,true);assert.match(d.error,/may have been recorded/);d.close();ui.controller._test.open('publish_policy');assert.equal(ui.dialogs.length,1);ui.click('[data-mp="retry"]',true);await ui.dialogs.at(-1).click();const writes=ui.requests.filter(r=>r.method==='POST');assert.equal(writes.length,2);assert.equal(writes[0].body,writes[1].body);assert.equal(writes[0].headers['x-atrium-planning-form'],writes[1].headers['x-atrium-planning-form']);assert.equal(ui.controller.pending,false)})
test('wrong receipt identity, version and outcome never claim a saved plan',async()=>{for(const change of [{id:'wrong-plan'},{version:99},{requestId:'wrong-request'},{action:'withdraw_plan'},{outcome:'completed'},{}]){const ui=portal();await ui.mount();ui.setHandler((path,init)=>init?.method==='POST'?result(ui.body({receipt:{...ui.receipt(JSON.parse(init.body)),...change,...(!Object.keys(change).length?{outcome:undefined}:{})}})):ui.defaultHandler(path,init));ui.controller._test.open('prepare_plan');const d=ui.dialogs.at(-1);fill(d,prepareValues);await d.click();await d.click();assert.equal(ui.controller.pending,true);assert.equal(ui.toasts.length,0)}})
test('decision emergency receipt is explicit, advances only the named held revision and never claims approval',async()=>{const ui=portal();await ui.mount();ui.setHandler((path,init)=>init?.method==='POST'?result(ui.body({receipt:ui.receipt(JSON.parse(init.body),{outcome:'emergency_held',version:3})})):ui.defaultHandler(path,init));ui.controller._test.open('decide_plan','approve');const d=ui.dialogs.at(-1);fill(d,{reason:'The resident says I smell gas'});d.body.handlers.get('input')();assert.match(d.body.querySelector('.mp-immediate-safety').innerHTML,/Act on immediate danger/);await d.click();assert.match(d.body.innerHTML,/Act on immediate danger/);await d.click();assert.equal(ui.controller.pending,false);assert.match(ui.toasts.at(-1).message,/plan was not approved/);const c={action:'decide_plan',requestId:'q',expectedPlanVersion:2};assert.throws(()=>ui.helpers.readReceipt({receipt:ui.receipt(c,{version:3,outcome:'saved'})},c),/could not be verified/)})
test('MFA requirement retains reviewed state but never automatically resubmits',async()=>{const ui=portal();await ui.mount();ui.setHandler((path,init)=>init?.method==='POST'?result({code:'planning_mfa_required',error:'Verify'},403):ui.defaultHandler(path,init));ui.controller._test.open('decide_plan','approve');const d=ui.dialogs.at(-1);fill(d,{reason:'Reviewed the exact scope and ceiling'});await d.click();await d.click();assert.equal(ui.controller.pending,true);assert.match(d.body.innerHTML,/href="\/api\/mfa"/);assert.match(d.error,/No change will be retried automatically/);const count=ui.requests.length;await d.click();assert.equal(d.closed,true);assert.equal(ui.requests.length,count);ui.closeView(true);assert.equal(ui.controller.pending,false)})
test('vendor reported availability, expiry and missing dates never imply appointment confirmation',async()=>{const ui=portal();await ui.mount('directory');assert.match(ui.host.innerHTML,/Availability not established/);assert.match(ui.host.innerHTML,/not a live calendar or confirmed appointment/);assert.match(ui.helpers.availability(vendor({availability:'available',availabilityObservedAt:prior,availabilityValidUntil:'2026-09-02T14:00:00.000Z'})),/expired/);assert.match(ui.helpers.availability(vendor({availability:'available',availabilityObservedAt:prior,availabilityValidUntil:until})),/Reported available · no appointment/);assert.throws(()=>ui.helpers.readVendor(vendor({availability:'available'})),/could not be verified/)})
test('source time uses property zone, preserves precision and refuses DST ambiguity',()=>{const h=portal().helpers;assert.equal(h.sourceInstant('2026-09-01T09:00',prior),prior);assert.equal(h.sourceInstant('2026-09-01T09:00'),'2026-09-01T14:00:00.000Z');assert.throws(()=>h.sourceInstant('2026-11-01T01:30'),/clock change/)})
test('emergency held plan/history remain visible and only withdrawal is offered',async()=>{const ui=portal();ui.setHandler((path,init)=>path.includes('resource=plan&')?result(ui.body({detail:detail({plan:plan({version:3,emergencyKinds:['gas']}),assessment:assessment({tier:'emergency',readiness:'emergency_review',reasons:['Follow the emergency protocol.']}),canDecide:false,history:[history({kind:'safety_hold',planVersion:3})]}),safetyInstructions:['Leave the area safely.'],safetyCallEmergencyServices:true})):ui.defaultHandler(path,init));await ui.mount();assert.match(ui.host.innerHTML,/Leave the area safely/);assert.match(ui.host.innerHTML,/Safety concern recorded/);assert.equal(ui.host.querySelector('[data-mp="approve"]'),null);assert.equal(ui.host.querySelector('[data-mp="prepare"]').disabled,true);assert.equal(ui.host.querySelector('[data-mp="withdraw"]').disabled,false)})
test('policy and vendor reviews preserve full manifests and unchanged source precision',async()=>{
 for(const action of ['publish_policy','save_vendor']){
  const ui=portal();await ui.mount('directory');ui.controller._test.open(action);const d=ui.dialogs.at(-1);fill(d,{reason:'Reviewed the approved evidence'});await d.click();assert.equal(d.error,null);await d.click();const c=JSON.parse(ui.requests.find(r=>r.method==='POST').body)
  assert.equal(c.details.observedAt,prior);assert.equal(c.details.validUntil,until);assert.equal(c.expectedVersion,action==='save_vendor'?3:2);assert.equal(c.details.sourceReference,action==='save_vendor'?'Synthetic approved directory':'Synthetic owner rules');assert.equal(ui.controller.pending,false)
 }
 const ui=portal();await ui.mount('directory');ui.controller._test.open('publish_policy');const d=ui.dialogs.at(-1);fill(d,{automatic:'100.00','automatic-category-plumbing':true,'excluded-plumbing':true,reason:'This must remain unsubmitted'});await d.click();assert.match(d.error,/cannot overlap/);assert.equal(ui.requests.filter(r=>r.method==='POST').length,0)
})
test('ordinary approve/reject preserve plan version while withdrawal advances it',async()=>{
 for(const action of ['approve','reject','withdraw']){const ui=portal();await ui.mount();ui.controller._test.open(action==='withdraw'?'withdraw_plan':'decide_plan',action==='withdraw'?null:action);const d=ui.dialogs.at(-1);fill(d,{reason:'Exact reviewed scope and cost'});await d.click();assert.match(d.body.innerHTML,/\$250\.00/);await d.click();const c=JSON.parse(ui.requests.find(r=>r.method==='POST').body);assert.equal(c.planId,'plan-one');assert.equal(c.expectedPlanVersion,2);assert.equal(ui.controller.pending,false);assert.equal(ui.toasts.length,1)}
})
test('vendor paging retains list scroll and final keyboard focus; older detail cannot replace newer selection',async()=>{
 const ui=portal();ui.setHandler((path,init)=>path.includes('resource=vendors')?result(ui.body({vendors:[vendor()],nextCursor:{id:'vendor-one',createdAt:prior}})):ui.defaultHandler(path,init));await ui.mount('directory');ui.host.querySelector('.mp-vendor-list').scrollTop=222;ui.host.querySelector('[data-mp="more"]').focus();ui.setHandler((path,init)=>path.includes('resource=vendors')?result(ui.body({vendors:[vendor({id:'vendor-two'})],nextCursor:null})):ui.defaultHandler(path,init));await ui.controller._test.load(true);assert.equal(ui.controller._test.state().vendors.length,2);assert.equal(ui.host.querySelector('.mp-vendor-list').scrollTop,222);assert.equal(ui.document.activeElement.dataset.mpVendor,'vendor-two')
 let finish;ui.setHandler(()=>new Promise(resolve=>{finish=resolve}));const old=ui.controller._test.chooseVendor('vendor-one');ui.setHandler(ui.defaultHandler);await ui.controller._test.chooseVendor('vendor-two');finish(result(ui.body({vendor:vendor()})));await old;assert.equal(ui.controller._test.state().vendor.id,'vendor-two')
})
test('history continuation keeps exact cursor and restores focus when the final button disappears',async()=>{
 const ui=portal();ui.setHandler((path,init)=>path.includes('resource=plan&')?result(ui.body({detail:detail({nextHistoryCursor:{id:'history-one',createdAt:prior}}),safetyInstructions:[],safetyCallEmergencyServices:false})):path.includes('resource=history')?result(ui.body({history:[history({id:'history-two',kind:'rejected'})],nextCursor:null})):ui.defaultHandler(path,init));await ui.mount();await ui.controller._test.moreHistory();assert.equal(ui.controller._test.state().detail.history.length,2);assert.equal(ui.document.activeElement.dataset.mpHeading,'');assert.ok(ui.requests.at(-1).path.includes(encodeURIComponent(prior)));assert.equal(ui.host.querySelector('[data-mp="history"]'),null)
})
test('an unresolved mutation is bounded, excludes duplicate clicks and retains one command',async()=>{
 const ui=portal();await ui.mount();let finish;ui.setHandler((path,init)=>init?.method==='POST'?new Promise(resolve=>{finish=resolve}):ui.defaultHandler(path,init));ui.controller._test.open('prepare_plan');const d=ui.dialogs.at(-1);fill(d,{...prepareValues,maximum:''});await d.click();const inFlight=d.click();await settle();await d.click();assert.equal(ui.requests.filter(r=>r.method==='POST').length,1);assert.equal(JSON.parse(ui.requests.at(-1).body).details.maximumCents,null);await ui.expire();await inFlight;assert.equal(ui.controller.busy,false);assert.equal(ui.controller.pending,true);assert.match(d.error,/unconfirmed/);const c=JSON.parse(ui.requests.find(r=>r.method==='POST').body);finish(result(ui.body({receipt:ui.receipt(c)})));await settle();assert.equal(ui.toasts.length,0)
})
test('postcommit sign-out keeps an explicit reconciliation warning until deliberate navigation',async()=>{
 const ui=portal();ui.markBooted();await ui.mount();ui.setHandler((path,init)=>init?.method==='POST'?result({code:'unauthenticated',error:'Sign in'},401):ui.defaultHandler(path,init));ui.controller._test.open('prepare_plan');const d=ui.dialogs.at(-1);fill(d,prepareValues);await d.click();await d.click();assert.equal(ui.reloads(),0);assert.equal(ui.host.hidden,true);assert.match(ui.window.planningAppTest.accessIssue().message,/may have been recorded/);assert.equal(ui.toasts.length,0);assert.equal(ui.requests.filter(r=>r.method==='POST').length,1)
})
test('Service case integration mounts planning, vendors and shared mutation locks without new Service resource calls',async()=>{
 const ui=portal(),serviceRequest={...request(),requestOrigin:'staff_observation',description:'Drips after closing',reportedPriority:'routine',reporterName:null,reporterPhone:null,reporterEmail:null,accessNotes:'',createdAt:prior,updatedAt:prior,createdBy:'staff-one',residentId:null,intakeLocation:{kind:'common_area',label:'Lobby'},residentIdAtIntake:null,residentVersionAtIntake:null,residentNameAtIntake:null,callerIdentityVerified:false,entryAuthorized:false,dispatchStatus:'not_dispatched',notificationStatus:'not_sent'}
 ui.setHandler((path,init)=>{if(path.startsWith('/api/maintenance-plans'))return ui.defaultHandler(path,init);const q=new URL(path,'https://example.test').searchParams;if(q.get('resource')==='overview')return result(ui.body({canManageResidents:true,timeZone:'America/Chicago',units:[{id:'13L',label:'13L'}],formToken:'service-token'}));if(q.get('resource')==='requests')return result(ui.body({requests:[serviceRequest],nextCursor:null}));if(q.get('resource')==='request')return result(ui.body({detail:{request:serviceRequest,resident:detail().resident,events:[],eventsTruncated:false,nextEventsCursor:null,related:[],relatedTruncated:false},safetyInstructions:[],safetyCallEmergencyServices:false}));return result({},404)})
 const service=ui.mountService();ui.location.hash=ui.A.hashFor('services',{state:'planning'});ui.A.navigate=(name,params={})=>{ui.location.hash=ui.A.hashFor(name,params);service.view.render();ui.window.planningAppTest.emit('route',ui.A.route())};service.view.mount(ui.host);service.view.render();await settle();assert.ok(ui.host.querySelector('.sv-planning-case'), JSON.stringify({requests:ui.requests.map(r=>r.path),detail:ui.host.querySelector('.sv-detail')?.innerHTML,errors:ui.host.querySelector('.sv-errors')?.innerHTML}));assert.match(ui.host.querySelector('.sv-planning-case').innerHTML,/Manager approval needed/)
 const own=service.state().planning;own._test.open('prepare_plan');assert.equal(ui.host.querySelector('[data-command="note"]').disabled,true);ui.dialogs.at(-1).close();assert.equal(ui.host.querySelector('[data-command="note"]').disabled,false)
 ui.A.navigate('services',{tab:'vendors'});await settle();assert.equal(ui.host.querySelector('.sv-workspace').hidden,true);assert.match(ui.host.querySelector('.sv-planning-directory').innerHTML,/Example Plumbing/);assert.equal(ui.requests.filter(r=>r.path.startsWith('/api/resident-services')&&r.path.includes('resource=vendors')).length,0)
 ui.emitPage('pagehide');assert.equal(own.pending,false);assert.equal(own._test.state().overview,null)
})
test('suspending an expired vendor preserves evidence dates and clears availability without inventing a fresh review',async()=>{
 const ui=portal(),old=vendor({validUntil:'2026-09-03T14:00:00.000Z',availability:'available',availabilityObservedAt:prior,availabilityValidUntil:'2026-09-02T14:00:00.000Z'})
 ui.setHandler((path,init)=>path.includes('resource=vendors')?result(ui.body({vendors:[old],nextCursor:null})):ui.defaultHandler(path,init));await ui.mount('directory');ui.controller._test.open('save_vendor');const d=ui.dialogs.at(-1);fill(d,{status:'suspended',reason:'Remove approval until evidence is reviewed'});await d.click();assert.equal(d.error,null);assert.match(d.body.innerHTML,/Suspended/);await d.click();const c=JSON.parse(ui.requests.find(r=>r.method==='POST').body);assert.equal(c.details.status,'suspended');assert.equal(c.details.observedAt,prior);assert.equal(c.details.validUntil,old.validUntil);assert.equal(c.details.availability,'unknown');assert.equal(c.details.availabilityObservedAt,null);assert.equal(c.details.availabilityValidUntil,null)
})
