import type { AuthenticatedUser, AuthorizedScope } from '../auth/model.ts'
import type { MfaConfiguration, MfaFactor } from '../auth/mfa-model.ts'
import { assertManagedSession } from '../auth/session-management.ts'
import { assertAuthorizedScope } from '../auth/authorization.ts'
import { assertVerifiedConsentWebAuthn } from '../auth/consent-webauthn.ts'
import type { VerifiedConsentWebAuthn } from '../auth/consent-webauthn.ts'
import { ConsentError } from '../residents/consent-model.ts'
import type { ConsentErrorCode, ResidentConsentRepository, ConsentPolicy, ConsentRoster, ConsentAuthority, ConsentRequest, ConsentDecision, ConsentReceipt, ConsentStaffState, ConsentStaffCommand, ConsentHistoryPage, ConsentListQuery, ResidentConsentDetail, ResidentConsentPage, ConsentCeremony, ConsentCeremonyStart, ConsentCeremonyClaim, ConsentOwnCommand, ConsentHold, ConsentPublicTerms } from '../residents/consent-model.ts'
import { consentId, consentVersion, consentDigest, consentTime, consentRecordId, consentPurpose, parseConsentPolicy, parseConsentRoster, parseConsentAuthority, parseConsentStaffCommand, parseConsentGrant, parseConsentOwnCommand, parseConsentList, parseConsentEntryWindow } from '../residents/consent-validation.ts'
import { evaluateConsent } from '../residents/consent.ts'
import { DatabaseConnection } from './connection.ts'
import { scopeContext } from './scope.ts'

const codes:ConsentErrorCode[]=['consent_invalid_input','consent_unauthenticated','consent_forbidden','consent_not_found','consent_changed','consent_request_conflict','consent_held','consent_passkey_required','consent_ceremony_used','consent_rate_limited','consent_unavailable']
const fail=(code:ConsentErrorCode='consent_unavailable'):never=>{throw new ConsentError(code)}
function check(value:unknown):asserts value{if(!value)fail()}
function object(v:any):Record<string,any>{check(v&&typeof v==='object'&&!Array.isArray(v));return v}
function pick(v:any,keys:string[]):any{const row=object(v),out:Record<string,unknown>={};for(const key of keys){check(Object.hasOwn(row,key));out[key]=row[key]}return out}
function list(v:unknown,max=100):any[]{check(Array.isArray(v)&&v.length<=max);return v}
const text=(v:unknown,max=4096):string=>{check(typeof v==='string'&&v.length<=max);return v}
const bool=(v:unknown):boolean=>{check(typeof v==='boolean');return v}
const nullableTime=(v:unknown)=>v===null?null:consentTime(v)
function safeError(raw:unknown):never{if(raw instanceof ConsentError)throw raw;const e=raw as {code?:string;message?:string};if(e?.code==='P0001'&&codes.includes(e.message as ConsentErrorCode))fail(e.message as ConsentErrorCode);if(['22023','22P02','22007','22008','23514','23502'].includes(e?.code??''))fail('consent_invalid_input');return fail()}
function policy(v:any):ConsentPolicy|null{if(v===null)return null;return {...parseConsentPolicy(pick(v,['enabled','funding','recipientRule','requireWorkConsent','noChargeStatement','recipientProtocol','entryProtocol','maximumResponseMinutes','maximumConsentMinutes','maximumEntryMinutes','helpLabel','helpPhone','helpUrl','emergencyInstructions','source'])),organizationId:consentRecordId(v.organizationId),propertyId:consentRecordId(v.propertyId),version:consentVersion(v.version),publishedBy:consentRecordId(v.publishedBy),publishedAt:consentTime(v.publishedAt),current:bool(v.current)}}
function roster(v:any):ConsentRoster|null{if(v===null)return null;return {...parseConsentRoster(pick(v,['unitId','members','source','complete','protocolCompleted'])),id:consentId(v.id),organizationId:consentRecordId(v.organizationId),propertyId:consentRecordId(v.propertyId),version:consentVersion(v.version),policyVersion:consentVersion(v.policyVersion),residencyDigest:consentDigest(v.residencyDigest),reviewedBy:consentRecordId(v.reviewedBy),reviewedAt:consentTime(v.reviewedAt),current:bool(v.current)}}
function authority(v:any):ConsentAuthority{return {...parseConsentAuthority(pick(v,['bindingId','bindingVersion','residentId','residentVersion','purpose','source','protocolCompleted'])),id:consentId(v.id),organizationId:consentRecordId(v.organizationId),propertyId:consentRecordId(v.propertyId),version:consentVersion(v.version),policyVersion:consentVersion(v.policyVersion),userId:consentRecordId(v.userId),unitId:consentRecordId(v.unitId),reviewedBy:consentRecordId(v.reviewedBy),reviewedAt:consentTime(v.reviewedAt),revokedAt:nullableTime(v.revokedAt),current:bool(v.current)}}
function party(v:any):ConsentPublicTerms['party']{if(v?.kind==='internal')return {kind:'internal',name:text(v.name,160)};check(v?.kind==='vendor');return {kind:'vendor',id:consentId(v.id),version:consentVersion(v.version),name:text(v.name,160)}}
function terms(v:any):ConsentPublicTerms{check(v?.schemaVersion===1&&v.funding==='property_no_resident_charge'&&v.currency==='USD'&&v.residentChargeCents===0&&Number.isSafeInteger(v.propertyMaximumCents)&&v.propertyMaximumCents>=0&&v.propertyMaximumCents<=1e9&&['unit_entry','no_unit_entry'].includes(v.accessRequirement));return {schemaVersion:1,purpose:consentPurpose(v.purpose),propertyName:text(v.propertyName,200),unitId:consentRecordId(v.unitId),publicSummary:text(v.publicSummary,1000),scopeOfWork:text(v.scopeOfWork,4000),party:party(v.party),funding:'property_no_resident_charge',currency:'USD',propertyMaximumCents:v.propertyMaximumCents,residentChargeCents:0,noChargeStatement:text(v.noChargeStatement,1000),accessRequirement:v.accessRequirement,entryWindow:v.entryWindow===null?null:parseConsentEntryWindow(v.entryWindow),conditions:text(v.conditions,2000)}}
function request(v:any):ConsentRequest|null{if(v===null)return null;return {id:consentId(v.id),organizationId:consentRecordId(v.organizationId),propertyId:consentRecordId(v.propertyId),caseId:consentId(v.caseId),purpose:consentPurpose(v.purpose),version:consentVersion(v.version),caseVersion:consentVersion(v.caseVersion),planId:consentId(v.planId),planVersion:consentVersion(v.planVersion),configurationVersion:consentVersion(v.configurationVersion),maintenancePolicyVersion:consentVersion(v.maintenancePolicyVersion),consentPolicyVersion:consentVersion(v.consentPolicyVersion),rosterId:consentId(v.rosterId),rosterVersion:consentVersion(v.rosterVersion),materialDigest:consentDigest(v.materialDigest),termsDigest:consentDigest(v.termsDigest),terms:terms(v.terms),responseDeadline:consentTime(v.responseDeadline),consentValidUntil:consentTime(v.consentValidUntil),publishedBy:consentRecordId(v.publishedBy),publishedAt:consentTime(v.publishedAt),createdAt:consentTime(v.createdAt),withdrawnAt:nullableTime(v.withdrawnAt)}}
function decision(v:any):ConsentDecision|null{if(v===null)return null;check(['grant','decline','revoke'].includes(v.decision));return {id:consentId(v.id),requestId:consentId(v.requestId),requestVersion:consentVersion(v.requestVersion),purpose:consentPurpose(v.purpose),version:consentVersion(v.version),actorUserId:consentRecordId(v.actorUserId),decision:v.decision,grantId:v.grantId===null?null:consentId(v.grantId),termsDigest:consentDigest(v.termsDigest),decidedAt:consentTime(v.decidedAt)}}
const holdValues:ConsentHold[]=['unconfigured','not_required','missing_plan','spending_not_authorized','emergency','context_changed','policy_changed','roster_changed','authority_changed','binding_changed','account_changed','factor_revoked','terms_changed','request_withdrawn','response_expired','consent_expired','entry_expired','missing_entry_window','missing_required_recipient','awaiting_decisions','declined','revoked','job_already_committed']
function holds(v:any):ConsentHold[]{return list(v,1000).map(x=>{check(holdValues.includes(x));return x})}
function effectiveness(v:any){check(v?.dispatchStatus==='not_dispatched'&&v.notificationStatus==='not_sent');return {required:bool(v.required),effective:bool(v.effective),holds:holds(v.holds),evaluatedAt:consentTime(v.evaluatedAt),refreshAt:nullableTime(v.refreshAt),dispatchStatus:'not_dispatched' as const,notificationStatus:'not_sent' as const}}
function help(v:any){return v===null?null:{label:text(v.label,120),phone:text(v.phone,16),url:v.url===null?null:text(v.url,2000),emergencyInstructions:text(v.emergencyInstructions,2000)}}
function receipt(v:any):ConsentReceipt{check(['publish_policy','publish_roster','save_authority','revoke_authority','publish_request','withdraw_request','grant','decline','revoke'].includes(v?.action)&&['policy','roster','authority','request','decision'].includes(v.resource)&&v.outcome==='saved');return {commandId:consentId(v.commandId),action:v.action,resource:v.resource,id:consentRecordId(v.id),version:consentVersion(v.version),requestId:v.requestId===null?null:consentId(v.requestId),requestVersion:v.requestVersion===null?null:consentVersion(v.requestVersion),purpose:v.purpose===null?null:consentPurpose(v.purpose),actorUserId:consentRecordId(v.actorUserId),committedAt:consentTime(v.committedAt),replayed:bool(v.replayed),outcome:'saved'}}
function detail(v:any):ResidentConsentDetail|null{if(v===null)return null;return {requestId:consentId(v.requestId),requestVersion:consentVersion(v.requestVersion),purpose:consentPurpose(v.purpose),termsDigest:consentDigest(v.termsDigest),materialDigest:consentDigest(v.materialDigest),terms:terms(v.terms),responseDeadline:consentTime(v.responseDeadline),consentValidUntil:consentTime(v.consentValidUntil),publishedAt:consentTime(v.publishedAt),withdrawnAt:nullableTime(v.withdrawnAt),ownDecision:decision(v.ownDecision),ownDecisionVersion:consentVersion(v.ownDecisionVersion,true),effectiveness:effectiveness(v.effectiveness),canGrant:bool(v.canGrant),canDecline:bool(v.canDecline),canRevoke:v.canRevoke===null?false:bool(v.canRevoke),requiresPasskey:bool(v.requiresPasskey),currentTerms:bool(v.currentTerms),help:help(v.help)}}
function factor(v:any):MfaFactor{check(v?.status==='active'&&Number.isSafeInteger(v.counter)&&v.counter>=0&&v.counter<=4294967295&&Number.isSafeInteger(v.createdAt)&&v.createdAt>0&&(v.lastUsedAt===null||Number.isSafeInteger(v.lastUsedAt)));return {id:consentId(v.id),label:text(v.label,100),credentialId:text(v.credentialId,1364),publicKey:text(v.publicKey,10000),counter:v.counter,counterRevision:consentVersion(v.counterRevision),status:'active',backupEligible:bool(v.backupEligible),backedUp:bool(v.backedUp),transports:list(v.transports,10).map(x=>text(x,40)),createdAt:v.createdAt,lastUsedAt:v.lastUsedAt}}
function claim(v:any):ConsentCeremonyClaim{check(v?.audience==='resident'&&Number.isSafeInteger(v.expiresAt)&&v.expiresAt>0);return {id:consentId(v.id),attemptId:consentId(v.attemptId),responseDigest:consentDigest(v.responseDigest),challengeHash:consentDigest(v.challengeHash),userId:consentRecordId(v.userId),sessionId:consentId(v.sessionId),credentialVersion:consentVersion(v.credentialVersion),securityVersion:consentVersion(v.securityVersion),origin:text(v.origin,2048),rpId:text(v.rpId,253),userHandle:text(v.userHandle,128),expiresAt:v.expiresAt,factor:factor(v.factor),audience:'resident',organizationId:consentRecordId(v.organizationId),propertyId:consentRecordId(v.propertyId),requestId:consentId(v.requestId),requestVersion:consentVersion(v.requestVersion),purpose:consentPurpose(v.purpose),termsDigest:consentDigest(v.termsDigest),materialDigest:consentDigest(v.materialDigest),commandId:consentId(v.commandId),expectedDecisionVersion:consentVersion(v.expectedDecisionVersion,true)}}

/** Finite commands own their full sorted-user admission fence. No nested property transaction. */
export class PostgresResidentConsentRepository implements ResidentConsentRepository{
 readonly app:DatabaseConnection;readonly auth:DatabaseConnection;readonly configuration:MfaConfiguration
 constructor(app:DatabaseConnection,auth:DatabaseConnection,configuration:MfaConfiguration){check(app.role==='atrium_app'&&auth.role==='atrium_authenticator');this.app=app;this.auth=auth;this.configuration={...configuration}}
 private async staff(scope:AuthorizedScope,configurationVersion:number,mode:'state'|'history'|'execute'|'receipt',caseId:string,input:Record<string,unknown>,proof:string|null=null):Promise<Record<string,any>>{
  assertAuthorizedScope(scope,mode==='execute'&& !['publish_request','withdraw_request'].includes(String((input.command as any)?.action))?'configure':'operate');if(scope.actor.kind!=='user'||!scope.actor.sessionId)fail('consent_forbidden')
  try{return await this.app.transaction(scopeContext(scope),async client=>{const out=await client.query('SELECT atrium.consent_staff($1,$2::jsonb,$3::bigint,$4::uuid) result',[mode,JSON.stringify({...input,caseId:consentId(caseId)}),consentVersion(configurationVersion),proof===null?null:consentId(proof)]);return object(out.rows[0]?.result)})}catch(e){return safeError(e)}
 }
 private async own(principal:AuthenticatedUser,mode:string,input:Record<string,unknown>):Promise<Record<string,any>>{
  try{assertManagedSession(principal)}catch{fail('consent_unauthenticated')}if(principal.audience!=='resident')fail('consent_forbidden')
  try{const result=await this.auth.transaction({actorUserId:principal.userId,actorSessionId:consentId(principal.sessionId),credentialVersion:principal.credentialVersion,sessionAudience:'resident'},async client=>{const out=await client.query('SELECT atrium.consent_resident($1,$2::jsonb) result',[mode,JSON.stringify(input)]);return object(out.rows[0]?.result)});if(result.error){check(codes.includes(result.error));fail(result.error)}return result}catch(e){return safeError(e)}
 }
 async staffState(scope:AuthorizedScope,configurationVersion:number,caseId:string):Promise<ConsentStaffState>{
  const out=await this.staff(scope,configurationVersion,'state',caseId,{}),v=object(out.data),now=new Date(consentTime(out.evaluatedAt));check(v.caseId===caseId&&v.organizationId===scope.organizationId&&v.propertyId===scope.propertyId&&v.configurationVersion===configurationVersion)
  const purposes=list(v.purposes,2).map(p=>{const g=object(p.graph),required=bool(g.required),r=request(g.request),recipients=list(g.recipients,50).map(m=>({residentId:consentId(m.residentId),residentVersion:consentVersion(m.residentVersion),bindingId:consentId(m.bindingId),bindingVersion:consentVersion(m.bindingVersion),userId:consentRecordId(m.userId),authorityId:consentId(m.authorityId),authorityVersion:consentVersion(m.authorityVersion),purpose:consentPurpose(m.purpose),displayName:text(m.displayName,200),decision:decision(m.decision),holds:holds(m.holds)}));return {purpose:consentPurpose(p.purpose),request:r,recipients,effectiveness:evaluateConsent({required,request:r,recipients,holds:holds(g.holds),deadlines:list(g.deadlines,1000).map(consentTime)},now)}})
  check(purposes.length===2&&purposes[0]?.purpose==='work'&&purposes[1]?.purpose==='entry')
  return {organizationId:scope.organizationId,propertyId:scope.propertyId,configurationVersion,caseId,caseVersion:consentVersion(v.caseVersion),unitId:v.unitId===null?null:consentRecordId(v.unitId),timeZone:text(v.timeZone,100),policy:policy(v.policy),roster:roster(v.roster),authorities:list(v.authorities,100).map(authority),residents:list(v.residents,50).map(r=>({id:consentId(r.id),version:consentVersion(r.version),displayName:text(r.displayName,200),unitId:consentRecordId(r.unitId),contextState:text(r.contextState,40),bindingId:r.bindingId===null?null:consentId(r.bindingId),bindingVersion:r.bindingVersion===null?null:consentVersion(r.bindingVersion)})),plan:v.plan===null?null:{id:consentId(v.plan.id),version:consentVersion(v.plan.version),scopeOfWork:text(v.plan.scopeOfWork,4000),maximumCents:v.plan.maximumCents,currency:'USD',accessRequirement:v.plan.accessRequirement,party:party(v.plan.party)},purposes:purposes as ConsentStaffState['purposes'],canPublishPolicy:bool(v.canPublishPolicy),canManageAuthority:bool(v.canManageAuthority),canPublishRequest:bool(v.canPublishRequest),help:help(v.help)}
 }
 private history(v:any,query:ConsentListQuery):ConsentHistoryPage{const rows=list(v.rows,query.limit+1),more=rows.length>query.limit,items=rows.slice(0,query.limit).map(r=>{check(['published','withdrawn','grant','decline','revoke'].includes(r.kind));return {id:consentId(r.id),requestId:consentId(r.requestId),requestVersion:consentVersion(r.requestVersion),purpose:consentPurpose(r.purpose),kind:r.kind,createdAt:consentTime(r.createdAt),decision:decision(r.decision),termsDigest:consentDigest(r.termsDigest),terms:terms(r.terms)}});const last=items.at(-1);return {items,nextCursor:more&&last?{id:last.id,createdAt:last.createdAt}:null}}
 async staffHistory(scope:AuthorizedScope,version:number,caseId:string,requestId:string,input:ConsentListQuery){const query=parseConsentList(input),out=await this.staff(scope,version,'history',caseId,{requestId:consentId(requestId),query});return this.history(out.data,query)}
 async staffReceipt(scope:AuthorizedScope,version:number,caseId:string,commandId:string){const out=await this.staff(scope,version,'receipt',caseId,{commandId:consentId(commandId)});return out.data===null?null:receipt(out.data)}
 async executeStaff(scope:AuthorizedScope,version:number,caseId:string,proofId:string|null,input:ConsentStaffCommand){const command=parseConsentStaffCommand(input);return receipt((await this.staff(scope,version,'execute',caseId,{command},proofId)).data)}
 async getOwn(principal:AuthenticatedUser,requestId:string){return detail((await this.own(principal,'detail',{requestId:consentId(requestId)})).data)}
 async listOwn(principal:AuthenticatedUser,input:ConsentListQuery):Promise<ResidentConsentPage>{const query=parseConsentList(input),out=await this.own(principal,'list',query as any),rows=list(out.data.rows,query.limit+1),selected=rows.slice(0,query.limit),details=selected.map(r=>{const d=detail(r.detail);check(d);return d}),refresh=details.flatMap(d=>d.effectiveness.refreshAt?[d.effectiveness.refreshAt]:[]).sort();const last=selected.at(-1);return {items:details.map(d=>({requestId:d.requestId,requestVersion:d.requestVersion,purpose:d.purpose,propertyName:d.terms.propertyName,unitId:d.terms.unitId,publicSummary:d.terms.publicSummary,responseDeadline:d.responseDeadline,consentValidUntil:d.consentValidUntil,publishedAt:d.publishedAt,ownDecision:d.ownDecision?.decision??null,effective:d.effectiveness.effective,holds:d.effectiveness.holds,currentTerms:d.currentTerms})),nextCursor:rows.length>query.limit&&last?{id:consentId(last.id),createdAt:consentTime(last.createdAt)}:null,evaluatedAt:consentTime(out.evaluatedAt),refreshAt:refresh[0]??null}}
 async ownHistory(principal:AuthenticatedUser,requestId:string,input:ConsentListQuery){const query=parseConsentList(input);return this.history((await this.own(principal,'history',{requestId:consentId(requestId),query})).data,query)}
 async ownReceipt(principal:AuthenticatedUser,commandId:string){const out=await this.own(principal,'receipt',{commandId:consentId(commandId)});return out.data===null?null:receipt(out.data)}
 async beginGrant(principal:AuthenticatedUser,input:ConsentCeremonyStart):Promise<ConsentCeremony>{const {challengeId,challengeHash,expiresAt,...raw}=input,command=parseConsentGrant(raw);check(Number.isSafeInteger(expiresAt));const out=await this.own(principal,'begin',{command,challengeId:consentId(challengeId),challengeHash:consentDigest(challengeHash),expiresAt,origin:this.configuration.origin,rpId:this.configuration.rpId});const v=object(out.data);return {id:consentId(v.id),userId:consentRecordId(v.userId),sessionId:consentId(v.sessionId),credentialVersion:consentVersion(v.credentialVersion),securityVersion:consentVersion(v.securityVersion),origin:text(v.origin,2048),rpId:text(v.rpId,253),challengeHash:consentDigest(v.challengeHash),expiresAt:v.expiresAt,userHandle:text(v.userHandle,128),organizationId:consentRecordId(v.organizationId),propertyId:consentRecordId(v.propertyId),command:parseConsentGrant(v.command),factors:list(v.factors,10).map(factor)}}
 async claimGrant(principal:AuthenticatedUser,input:{challengeId:string;attemptId:string;responseDigest:string;credentialId:string}){return claim((await this.own(principal,'claim',{challengeId:consentId(input.challengeId),attemptId:consentId(input.attemptId),responseDigest:consentDigest(input.responseDigest),credentialId:text(input.credentialId,1364)})).data)}
 async rejectGrant(principal:AuthenticatedUser,c:ConsentCeremonyClaim){await this.own(principal,'reject',{challengeId:consentId(c.id),claim:claim(c)})}
 async finishGrant(principal:AuthenticatedUser,verified:VerifiedConsentWebAuthn){assertVerifiedConsentWebAuthn(verified);check(verified.claim.userId===principal.userId&&verified.claim.sessionId===principal.sessionId&&verified.claim.credentialVersion===principal.credentialVersion);return receipt((await this.own(principal,'finish',{challengeId:verified.claim.id,kind:verified.kind,claim:verified.claim,newCounter:verified.newCounter,backedUp:verified.backedUp})).data)}
 async decideOwn(principal:AuthenticatedUser,input:ConsentOwnCommand){return receipt((await this.own(principal,'decide',{command:parseConsentOwnCommand(input)})).data)}
}
