-- Development source for the first PostgreSQL slice. Not an applied migration.
-- Provision the three roles separately; see README.md. Supabase migration filenames
-- must be generated by its CLI before copying a reviewed version of this source.
CREATE SCHEMA atrium AUTHORIZATION atrium_admin;
REVOKE ALL ON SCHEMA atrium FROM PUBLIC;
SET LOCAL ROLE atrium_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA atrium REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA atrium REVOKE ALL ON TABLES FROM PUBLIC;

CREATE DOMAIN atrium.record_id AS text
  CHECK (VALUE ~ '^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$');
CREATE DOMAIN atrium.positive_version AS bigint
  CHECK (VALUE BETWEEN 1 AND 9007199254740991);

CREATE FUNCTION atrium.context(setting_name text) RETURNS text
  LANGUAGE sql STABLE SECURITY INVOKER SET search_path = pg_catalog
  AS $$ SELECT nullif(current_setting('atrium.' || setting_name, true), '') $$;

CREATE FUNCTION atrium.valid_time_zone(zone text) RETURNS boolean
  LANGUAGE sql STABLE SECURITY INVOKER SET search_path = pg_catalog
  AS $$ SELECT EXISTS (SELECT 1 FROM pg_timezone_names WHERE name = zone) $$;

CREATE TABLE atrium.users (
  id atrium.record_id PRIMARY KEY,
  username text NOT NULL UNIQUE CHECK (username ~ '^[a-z0-9][a-z0-9._-]{2,63}$'),
  display_name text NOT NULL CHECK (length(btrim(display_name)) BETWEEN 1 AND 200),
  status text NOT NULL CHECK (status IN ('active', 'inactive')),
  credential_version atrium.positive_version NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE atrium.user_credentials (
  user_id atrium.record_id PRIMARY KEY REFERENCES atrium.users(id),
  password_hash text NOT NULL CHECK (length(password_hash) BETWEEN 20 AND 2048),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE atrium.organizations (
  id atrium.record_id PRIMARY KEY,
  name text NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 200),
  status text NOT NULL CHECK (status IN ('active', 'inactive')),
  permission_version atrium.positive_version NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE atrium.memberships (
  id atrium.record_id PRIMARY KEY,
  user_id atrium.record_id NOT NULL REFERENCES atrium.users(id),
  organization_id atrium.record_id NOT NULL REFERENCES atrium.organizations(id),
  role text NOT NULL CHECK (role IN ('owner', 'admin', 'staff', 'viewer')),
  status text NOT NULL CHECK (status IN ('active', 'revoked')),
  access text NOT NULL CHECK (access IN ('organization', 'properties')),
  permission_version atrium.positive_version NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, organization_id),
  UNIQUE (organization_id, id)
);
CREATE INDEX memberships_organization_idx ON atrium.memberships (organization_id, user_id);

CREATE TABLE atrium.properties (
  id atrium.record_id PRIMARY KEY,
  organization_id atrium.record_id NOT NULL REFERENCES atrium.organizations(id),
  name text NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 200),
  time_zone text NOT NULL CHECK (atrium.valid_time_zone(time_zone)),
  status text NOT NULL CHECK (status IN ('active', 'inactive')),
  permission_version atrium.positive_version NOT NULL DEFAULT 1,
  published_configuration_version atrium.positive_version,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (organization_id, id)
);

CREATE TABLE atrium.property_grants (
  membership_id atrium.record_id NOT NULL,
  organization_id atrium.record_id NOT NULL,
  property_id atrium.record_id NOT NULL,
  status text NOT NULL CHECK (status IN ('active', 'revoked')),
  permission_version atrium.positive_version NOT NULL DEFAULT 1,
  PRIMARY KEY (membership_id, property_id),
  FOREIGN KEY (organization_id, membership_id)
    REFERENCES atrium.memberships(organization_id, id),
  FOREIGN KEY (organization_id, property_id)
    REFERENCES atrium.properties(organization_id, id)
);
CREATE INDEX property_grants_property_idx ON atrium.property_grants (organization_id, property_id);
CREATE INDEX property_grants_membership_owner_idx ON atrium.property_grants (organization_id, membership_id);

CREATE TABLE atrium.property_configurations (
  organization_id atrium.record_id NOT NULL,
  property_id atrium.record_id NOT NULL,
  version atrium.positive_version NOT NULL,
  schema_version integer NOT NULL DEFAULT 1 CHECK (schema_version > 0),
  status text NOT NULL CHECK (status IN ('draft', 'published', 'retired')),
  -- Validated complete property/inventory/floorplans/knowledge envelope, never secrets.
  configuration jsonb NOT NULL CHECK (jsonb_typeof(configuration) = 'object'),
  inventory_read_at timestamptz NOT NULL,
  inventory_source text NOT NULL CHECK (length(btrim(inventory_source)) BETWEEN 1 AND 200),
  created_at timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz,
  PRIMARY KEY (organization_id, property_id, version),
  FOREIGN KEY (organization_id, property_id)
    REFERENCES atrium.properties(organization_id, id),
  CHECK ((status = 'draft' AND published_at IS NULL) OR
         (status IN ('published', 'retired') AND published_at IS NOT NULL)),
  CHECK (status = 'draft' OR coalesce(
    jsonb_typeof(configuration -> 'property') = 'object'
    AND configuration #>> '{property,id}' = property_id
    AND jsonb_typeof(configuration -> 'inventory') = 'array'
    AND jsonb_typeof(configuration -> 'floorplans') = 'array'
    AND jsonb_typeof(configuration -> 'knowledge') = 'array', false))
);
ALTER TABLE atrium.properties ADD CONSTRAINT properties_published_configuration_fk
  FOREIGN KEY (organization_id, id, published_configuration_version)
  REFERENCES atrium.property_configurations(organization_id, property_id, version)
  DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE atrium.channel_bindings (
  id atrium.record_id PRIMARY KEY,
  provider text NOT NULL CHECK (provider ~ '^[a-z][a-z0-9_-]{0,63}$'),
  external_id text NOT NULL CHECK (length(external_id) BETWEEN 1 AND 256
    AND external_id !~ '[[:space:][:cntrl:]]'),
  organization_id atrium.record_id NOT NULL,
  property_id atrium.record_id NOT NULL,
  status text NOT NULL CHECK (status IN ('active', 'inactive')),
  capabilities text[] NOT NULL DEFAULT '{}' CHECK (
    capabilities <@ ARRAY['read', 'operate', 'configure', 'manage_members', 'manage_organization']::text[]
    AND array_position(capabilities, NULL) IS NULL),
  permission_version atrium.positive_version NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  -- This is a routing identity, unlike a provider record ID inside a property.
  UNIQUE (provider, external_id),
  UNIQUE (organization_id, property_id, id),
  FOREIGN KEY (organization_id, property_id)
    REFERENCES atrium.properties(organization_id, id)
);

-- Transitional adapters: identities are typed; domain payloads remain JSON until
-- their workflow repositories are normalized in a later migration.
CREATE TABLE atrium.operational_documents (
  organization_id atrium.record_id NOT NULL,
  property_id atrium.record_id NOT NULL,
  key text NOT NULL CHECK (length(key) BETWEEN 1 AND 512 AND key !~ '[[:cntrl:]]'),
  value jsonb NOT NULL,
  revision atrium.positive_version NOT NULL DEFAULT 1,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (organization_id, property_id, key),
  FOREIGN KEY (organization_id, property_id)
    REFERENCES atrium.properties(organization_id, id)
);
CREATE INDEX operational_documents_prefix_idx
  ON atrium.operational_documents (organization_id, property_id, key text_pattern_ops);

CREATE TABLE atrium.calendars (
  organization_id atrium.record_id NOT NULL,
  property_id atrium.record_id NOT NULL,
  state jsonb NOT NULL CHECK (jsonb_typeof(state) = 'object'
    AND coalesce(jsonb_typeof(state -> 'blocks') = 'array', false)
    AND coalesce(jsonb_typeof(state -> 'bookings') = 'array', false)),
  revision atrium.positive_version NOT NULL DEFAULT 1,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (organization_id, property_id),
  FOREIGN KEY (organization_id, property_id)
    REFERENCES atrium.properties(organization_id, id)
);

CREATE TABLE atrium.audit_events (
  organization_id atrium.record_id NOT NULL,
  property_id atrium.record_id NOT NULL,
  id atrium.record_id NOT NULL,
  operation text NOT NULL CHECK (operation IN ('document.set', 'document.update', 'document.delete', 'calendar.update')),
  record_key text NOT NULL CHECK (length(record_key) BETWEEN 1 AND 512 AND record_key !~ '[[:cntrl:]]'),
  actor_user_id atrium.record_id REFERENCES atrium.users(id),
  actor_channel_binding_id atrium.record_id,
  request_id atrium.record_id NOT NULL,
  configuration_version atrium.positive_version,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (organization_id, property_id, id),
  FOREIGN KEY (organization_id, property_id)
    REFERENCES atrium.properties(organization_id, id),
  FOREIGN KEY (organization_id, property_id, actor_channel_binding_id)
    REFERENCES atrium.channel_bindings(organization_id, property_id, id),
  FOREIGN KEY (organization_id, property_id, configuration_version)
    REFERENCES atrium.property_configurations(organization_id, property_id, version),
  CHECK (num_nonnulls(actor_user_id, actor_channel_binding_id) = 1)
);
CREATE INDEX audit_events_time_idx ON atrium.audit_events (organization_id, property_id, created_at, id);
CREATE INDEX audit_events_user_idx ON atrium.audit_events (actor_user_id) WHERE actor_user_id IS NOT NULL;
CREATE INDEX audit_events_binding_idx ON atrium.audit_events (organization_id, property_id, actor_channel_binding_id);
CREATE INDEX audit_events_configuration_idx ON atrium.audit_events (organization_id, property_id, configuration_version);

-- All helpers run with the caller's rights. The policy dependency graph is acyclic:
-- users -> memberships -> grants; bindings are context-selected; then org/property.
CREATE FUNCTION atrium.staff_context() RETURNS boolean
  LANGUAGE sql STABLE SECURITY INVOKER SET search_path = pg_catalog
  AS $$ SELECT atrium.context('actor_user_id') IS NOT NULL
    AND atrium.context('credential_version') IS NOT NULL
    AND atrium.context('channel_binding_id') IS NULL $$;

CREATE FUNCTION atrium.channel_context() RETURNS boolean
  LANGUAGE sql STABLE SECURITY INVOKER SET search_path = pg_catalog
  AS $$ SELECT atrium.context('channel_binding_id') IS NOT NULL
    AND atrium.context('channel_binding_version') IS NOT NULL
    AND atrium.context('actor_user_id') IS NULL
    AND atrium.context('credential_version') IS NULL $$;

CREATE FUNCTION atrium.staff_property_permission(org_id text, prop_id text, permission text) RETURNS boolean
  LANGUAGE sql STABLE SECURITY INVOKER SET search_path = pg_catalog
  AS $$ SELECT atrium.staff_context() AND EXISTS (
    SELECT 1 FROM atrium.memberships m JOIN atrium.users u ON u.id = m.user_id
    WHERE m.user_id = atrium.context('actor_user_id') AND m.organization_id = org_id
      AND m.status = 'active' AND u.status = 'active'
      AND u.credential_version::text = atrium.context('credential_version')
      AND CASE permission WHEN 'read' THEN true WHEN 'operate' THEN m.role IN ('owner', 'admin', 'staff')
        WHEN 'configure' THEN m.role IN ('owner', 'admin')
        WHEN 'manage_members' THEN m.role IN ('owner', 'admin')
        WHEN 'manage_organization' THEN m.role = 'owner' ELSE false END
      AND (m.access = 'organization' OR EXISTS (
        SELECT 1 FROM atrium.property_grants g WHERE g.membership_id = m.id
          AND g.organization_id = org_id AND g.property_id = prop_id AND g.status = 'active'))
  ) $$;

CREATE FUNCTION atrium.channel_property_permission(org_id text, prop_id text, permission text) RETURNS boolean
  LANGUAGE sql STABLE SECURITY INVOKER SET search_path = pg_catalog
  AS $$ SELECT atrium.channel_context() AND EXISTS (
    SELECT 1 FROM atrium.channel_bindings b WHERE b.id = atrium.context('channel_binding_id')
      AND b.organization_id = org_id AND b.property_id = prop_id AND b.status = 'active'
      AND b.permission_version::text = atrium.context('channel_binding_version')
      AND permission = ANY(b.capabilities)
  ) $$;

CREATE FUNCTION atrium.can_access_property(org_id text, prop_id text, permission text) RETURNS boolean
  LANGUAGE sql STABLE SECURITY INVOKER SET search_path = pg_catalog
  AS $$ SELECT org_id = atrium.context('organization_id') AND prop_id = atrium.context('property_id')
    AND EXISTS (SELECT 1 FROM atrium.organizations o WHERE o.id = org_id AND o.status = 'active')
    AND EXISTS (SELECT 1 FROM atrium.properties p WHERE p.id = prop_id
      AND p.organization_id = org_id AND p.status = 'active')
    AND (atrium.staff_property_permission(org_id, prop_id, permission)
      OR atrium.channel_property_permission(org_id, prop_id, permission)) $$;

DO $$
DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['users', 'user_credentials', 'organizations', 'memberships',
    'properties', 'property_grants', 'property_configurations', 'channel_bindings',
    'operational_documents', 'calendars', 'audit_events']
  LOOP
    EXECUTE format('ALTER TABLE atrium.%I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('ALTER TABLE atrium.%I FORCE ROW LEVEL SECURITY', table_name);
    EXECUTE format('CREATE POLICY maintenance ON atrium.%I TO atrium_admin USING (true) WITH CHECK (true)', table_name);
  END LOOP;
END $$;

CREATE POLICY app_self ON atrium.users FOR SELECT TO atrium_app USING (
  atrium.staff_context() AND id = atrium.context('actor_user_id') AND status = 'active'
  AND credential_version::text = atrium.context('credential_version'));
CREATE POLICY auth_identity ON atrium.users FOR SELECT TO atrium_authenticator USING (
  id = atrium.context('actor_user_id') OR username = atrium.context('login_username'));
CREATE POLICY auth_password ON atrium.user_credentials FOR SELECT TO atrium_authenticator USING (
  EXISTS (SELECT 1 FROM atrium.users u WHERE u.id = user_credentials.user_id
    AND u.username = atrium.context('login_username') AND u.status = 'active'));

CREATE POLICY app_membership ON atrium.memberships FOR SELECT TO atrium_app USING (
  user_id = atrium.context('actor_user_id') AND organization_id = atrium.context('organization_id')
  AND status = 'active' AND EXISTS (SELECT 1 FROM atrium.users u WHERE u.id = memberships.user_id));
CREATE POLICY auth_membership ON atrium.memberships FOR SELECT TO atrium_authenticator USING (
  user_id = atrium.context('actor_user_id') AND EXISTS (SELECT 1 FROM atrium.users u
    WHERE u.id = memberships.user_id AND u.status = 'active'
      AND u.credential_version::text = atrium.context('credential_version')));
CREATE POLICY app_grant ON atrium.property_grants FOR SELECT TO atrium_app USING (
  organization_id = atrium.context('organization_id') AND status = 'active'
  AND EXISTS (SELECT 1 FROM atrium.memberships m WHERE m.id = property_grants.membership_id
    AND m.organization_id = property_grants.organization_id));
CREATE POLICY auth_grant ON atrium.property_grants FOR SELECT TO atrium_authenticator USING (
  EXISTS (SELECT 1 FROM atrium.memberships m WHERE m.id = property_grants.membership_id
    AND m.organization_id = property_grants.organization_id));

CREATE POLICY app_binding ON atrium.channel_bindings FOR SELECT TO atrium_app USING (
  atrium.channel_context() AND id = atrium.context('channel_binding_id') AND status = 'active'
  AND permission_version::text = atrium.context('channel_binding_version'));
CREATE POLICY auth_binding ON atrium.channel_bindings FOR SELECT TO atrium_authenticator USING (
  provider = atrium.context('channel_provider') AND external_id = atrium.context('channel_external_id'));

CREATE POLICY app_organization ON atrium.organizations FOR SELECT TO atrium_app USING (
  id = atrium.context('organization_id') AND status = 'active' AND (
    EXISTS (SELECT 1 FROM atrium.memberships m WHERE m.organization_id = organizations.id)
    OR EXISTS (SELECT 1 FROM atrium.channel_bindings b WHERE b.organization_id = organizations.id)));
CREATE POLICY auth_organization ON atrium.organizations FOR SELECT TO atrium_authenticator USING (
  EXISTS (SELECT 1 FROM atrium.memberships m WHERE m.organization_id = organizations.id AND m.status = 'active')
  OR EXISTS (SELECT 1 FROM atrium.channel_bindings b WHERE b.organization_id = organizations.id));

CREATE POLICY app_property ON atrium.properties FOR SELECT TO atrium_app USING (
  organization_id = atrium.context('organization_id') AND id = atrium.context('property_id')
  AND status = 'active' AND EXISTS (SELECT 1 FROM atrium.organizations o WHERE o.id = properties.organization_id)
  AND (atrium.staff_property_permission(organization_id, id, 'read')
    OR atrium.channel_property_permission(organization_id, id, 'read')));
CREATE POLICY auth_property ON atrium.properties FOR SELECT TO atrium_authenticator USING (
  EXISTS (SELECT 1 FROM atrium.memberships m WHERE m.organization_id = properties.organization_id AND m.status = 'active'
    AND (m.access = 'organization' OR EXISTS (SELECT 1 FROM atrium.property_grants g
      WHERE g.membership_id = m.id AND g.organization_id = properties.organization_id
        AND g.property_id = properties.id AND g.status = 'active')))
  OR EXISTS (SELECT 1 FROM atrium.channel_bindings b
    WHERE b.organization_id = properties.organization_id AND b.property_id = properties.id));

CREATE POLICY app_configuration ON atrium.property_configurations FOR SELECT TO atrium_app USING (
  status = 'published' AND atrium.can_access_property(organization_id, property_id, 'read'));

DO $$
DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['operational_documents', 'calendars'] LOOP
    EXECUTE format('CREATE POLICY scoped_read ON atrium.%I FOR SELECT TO atrium_app USING (atrium.can_access_property(organization_id, property_id, ''read''))', table_name);
    EXECUTE format('CREATE POLICY scoped_insert ON atrium.%I FOR INSERT TO atrium_app WITH CHECK (atrium.can_access_property(organization_id, property_id, ''operate''))', table_name);
    EXECUTE format('CREATE POLICY scoped_update ON atrium.%I FOR UPDATE TO atrium_app USING (atrium.can_access_property(organization_id, property_id, ''operate'')) WITH CHECK (atrium.can_access_property(organization_id, property_id, ''operate''))', table_name);
  END LOOP;
END $$;
CREATE POLICY scoped_delete ON atrium.operational_documents FOR DELETE TO atrium_app
  USING (atrium.can_access_property(organization_id, property_id, 'operate'));
CREATE POLICY audit_read ON atrium.audit_events FOR SELECT TO atrium_app
  USING (atrium.can_access_property(organization_id, property_id, 'read'));
CREATE POLICY audit_append ON atrium.audit_events FOR INSERT TO atrium_app WITH CHECK (
  atrium.can_access_property(organization_id, property_id, 'operate') AND (
    (atrium.staff_context() AND actor_user_id = atrium.context('actor_user_id') AND actor_channel_binding_id IS NULL)
    OR (atrium.channel_context() AND actor_channel_binding_id = atrium.context('channel_binding_id') AND actor_user_id IS NULL)));

-- Published facts cannot be edited in place, even by the maintenance role. Retiring
-- a version preserves its payload. New facts require a new version/publication.
CREATE FUNCTION atrium.keep_published_configuration() RETURNS trigger
  LANGUAGE plpgsql SECURITY INVOKER SET search_path = pg_catalog AS $$
BEGIN
  IF OLD.status <> 'draft' THEN
    IF TG_OP = 'DELETE' THEN
      RAISE EXCEPTION 'Published configuration history cannot be deleted';
    END IF;
    IF NEW.organization_id IS DISTINCT FROM OLD.organization_id
      OR NEW.property_id IS DISTINCT FROM OLD.property_id OR NEW.version IS DISTINCT FROM OLD.version
      OR NEW.schema_version IS DISTINCT FROM OLD.schema_version
      OR NEW.configuration IS DISTINCT FROM OLD.configuration OR NEW.created_at IS DISTINCT FROM OLD.created_at
      OR NEW.inventory_read_at IS DISTINCT FROM OLD.inventory_read_at OR NEW.inventory_source IS DISTINCT FROM OLD.inventory_source
      OR NEW.published_at IS DISTINCT FROM OLD.published_at OR NEW.status = 'draft' THEN
      RAISE EXCEPTION 'Published configuration is immutable; create a new version';
    END IF;
  END IF;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER preserve_configuration BEFORE UPDATE OR DELETE ON atrium.property_configurations
  FOR EACH ROW EXECUTE FUNCTION atrium.keep_published_configuration();

-- A publication pointer can be changed in the same transaction as its new version,
-- but it must resolve to a published row when the transaction commits.
CREATE FUNCTION atrium.check_publication_pointer() RETURNS trigger
  LANGUAGE plpgsql SECURITY INVOKER SET search_path = pg_catalog AS $$
DECLARE target_org text; target_property text;
BEGIN
  IF TG_TABLE_NAME = 'properties' THEN
    target_org := NEW.organization_id; target_property := NEW.id;
  ELSE
    target_org := NEW.organization_id; target_property := NEW.property_id;
  END IF;
  IF EXISTS (SELECT 1 FROM atrium.properties p
      LEFT JOIN atrium.property_configurations c ON c.organization_id = p.organization_id
        AND c.property_id = p.id AND c.version = p.published_configuration_version
      WHERE p.organization_id = target_org AND p.id = target_property
        AND p.published_configuration_version IS NOT NULL
        AND (c.version IS NULL OR c.status <> 'published')) THEN
    RAISE EXCEPTION 'Current property configuration must be published';
  END IF;
  RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER property_publication AFTER INSERT OR UPDATE ON atrium.properties
  DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION atrium.check_publication_pointer();
CREATE CONSTRAINT TRIGGER configuration_publication AFTER INSERT OR UPDATE ON atrium.property_configurations
  DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION atrium.check_publication_pointer();

-- Password rotation cannot accidentally retain the old session version. The admin
-- may explicitly advance it further, but changing a hash always advances it once.
CREATE FUNCTION atrium.rotate_credential_version() RETURNS trigger
  LANGUAGE plpgsql SECURITY INVOKER SET search_path = pg_catalog AS $$
BEGIN
  IF TG_OP = 'UPDATE' AND NEW.user_id IS DISTINCT FROM OLD.user_id THEN
    RAISE EXCEPTION 'Credentials cannot be reassigned to another user';
  END IF;
  IF TG_OP = 'DELETE' OR NEW.password_hash IS DISTINCT FROM OLD.password_hash THEN
    UPDATE atrium.users SET credential_version = credential_version + 1 WHERE id = OLD.user_id;
  END IF;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  NEW.updated_at := clock_timestamp();
  RETURN NEW;
END $$;
CREATE TRIGGER credential_rotation BEFORE UPDATE OR DELETE ON atrium.user_credentials
  FOR EACH ROW EXECUTE FUNCTION atrium.rotate_credential_version();

CREATE FUNCTION atrium.advance_revision() RETURNS trigger
  LANGUAGE plpgsql SECURITY INVOKER SET search_path = pg_catalog AS $$
BEGIN
  NEW.revision := OLD.revision + 1;
  NEW.updated_at := clock_timestamp();
  RETURN NEW;
END $$;
CREATE TRIGGER document_revision BEFORE UPDATE ON atrium.operational_documents
  FOR EACH ROW EXECUTE FUNCTION atrium.advance_revision();
CREATE TRIGGER calendar_revision BEFORE UPDATE ON atrium.calendars
  FOR EACH ROW EXECUTE FUNCTION atrium.advance_revision();

REVOKE ALL ON ALL TABLES IN SCHEMA atrium FROM PUBLIC;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA atrium FROM PUBLIC;
REVOKE USAGE ON TYPE atrium.record_id, atrium.positive_version FROM PUBLIC;
GRANT USAGE ON SCHEMA atrium TO atrium_app, atrium_authenticator;
GRANT USAGE ON TYPE atrium.record_id, atrium.positive_version TO atrium_app, atrium_authenticator;
GRANT EXECUTE ON FUNCTION atrium.context(text), atrium.staff_context(), atrium.channel_context(),
  atrium.staff_property_permission(text, text, text), atrium.channel_property_permission(text, text, text),
  atrium.can_access_property(text, text, text) TO atrium_app, atrium_authenticator;
GRANT SELECT ON atrium.users, atrium.organizations, atrium.memberships, atrium.properties,
  atrium.property_grants, atrium.channel_bindings TO atrium_app, atrium_authenticator;
GRANT SELECT ON atrium.user_credentials TO atrium_authenticator;
GRANT SELECT ON atrium.property_configurations TO atrium_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON atrium.operational_documents TO atrium_app;
GRANT SELECT, INSERT, UPDATE ON atrium.calendars TO atrium_app;
GRANT SELECT, INSERT ON atrium.audit_events TO atrium_app;

RESET ROLE;
